// Code generated by MockGen. DO NOT EDIT.
// Source: oss_grpc.pb.go

// Package mock_s3 is a generated GoMock package.
package mock_s3

import (
	context "context"

	"mosn.io/layotto/spec/proto/extension/v1/s3"

	gomock "github.com/golang/mock/gomock"
	grpc "google.golang.org/grpc"
	metadata "google.golang.org/grpc/metadata"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// MockObjectStorageServiceClient is a mock of ObjectStorageServiceClient interface.
type MockObjectStorageServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockObjectStorageServiceClientMockRecorder
}

// MockObjectStorageServiceClientMockRecorder is the mock recorder for MockObjectStorageServiceClient.
type MockObjectStorageServiceClientMockRecorder struct {
	mock *MockObjectStorageServiceClient
}

// NewMockObjectStorageServiceClient creates a new mock instance.
func NewMockObjectStorageServiceClient(ctrl *gomock.Controller) *MockObjectStorageServiceClient {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockObjectStorageServiceClient) EXPECT() *MockObjectStorageServiceClientMockRecorder {
	_ = "STUB: not implemented"

	// AbortMultipartUpload mocks base method.
	return nil
}

func (m *MockObjectStorageServiceClient) AbortMultipartUpload(ctx context.Context, in *s3.AbortMultipartUploadInput, opts ...grpc.CallOption) (*s3.AbortMultipartUploadOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// AbortMultipartUpload indicates an expected call of AbortMultipartUpload.
func (mr *MockObjectStorageServiceClientMockRecorder) AbortMultipartUpload(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// AppendObject mocks base method.
func (m *MockObjectStorageServiceClient) AppendObject(ctx context.Context, opts ...grpc.CallOption) (s3.ObjectStorageService_AppendObjectClient, error) {
	_ = "STUB: not implemented"
	return *new(s3.ObjectStorageService_AppendObjectClient), nil
}

// AppendObject indicates an expected call of AppendObject.
func (mr *MockObjectStorageServiceClientMockRecorder) AppendObject(ctx interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// CompleteMultipartUpload mocks base method.
func (m *MockObjectStorageServiceClient) CompleteMultipartUpload(ctx context.Context, in *s3.CompleteMultipartUploadInput, opts ...grpc.CallOption) (*s3.CompleteMultipartUploadOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CompleteMultipartUpload indicates an expected call of CompleteMultipartUpload.
func (mr *MockObjectStorageServiceClientMockRecorder) CompleteMultipartUpload(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// CopyObject mocks base method.
func (m *MockObjectStorageServiceClient) CopyObject(ctx context.Context, in *s3.CopyObjectInput, opts ...grpc.CallOption) (*s3.CopyObjectOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CopyObject indicates an expected call of CopyObject.
func (mr *MockObjectStorageServiceClientMockRecorder) CopyObject(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// CreateMultipartUpload mocks base method.
func (m *MockObjectStorageServiceClient) CreateMultipartUpload(ctx context.Context, in *s3.CreateMultipartUploadInput, opts ...grpc.CallOption) (*s3.CreateMultipartUploadOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateMultipartUpload indicates an expected call of CreateMultipartUpload.
func (mr *MockObjectStorageServiceClientMockRecorder) CreateMultipartUpload(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// DeleteObject mocks base method.
func (m *MockObjectStorageServiceClient) DeleteObject(ctx context.Context, in *s3.DeleteObjectInput, opts ...grpc.CallOption) (*s3.DeleteObjectOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteObject indicates an expected call of DeleteObject.
func (mr *MockObjectStorageServiceClientMockRecorder) DeleteObject(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// DeleteObjectTagging mocks base method.
func (m *MockObjectStorageServiceClient) DeleteObjectTagging(ctx context.Context, in *s3.DeleteObjectTaggingInput, opts ...grpc.CallOption) (*s3.DeleteObjectTaggingOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteObjectTagging indicates an expected call of DeleteObjectTagging.
func (mr *MockObjectStorageServiceClientMockRecorder) DeleteObjectTagging(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// DeleteObjects mocks base method.
func (m *MockObjectStorageServiceClient) DeleteObjects(ctx context.Context, in *s3.DeleteObjectsInput, opts ...grpc.CallOption) (*s3.DeleteObjectsOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteObjects indicates an expected call of DeleteObjects.
func (mr *MockObjectStorageServiceClientMockRecorder) DeleteObjects(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetObject mocks base method.
func (m *MockObjectStorageServiceClient) GetObject(ctx context.Context, in *s3.GetObjectInput, opts ...grpc.CallOption) (s3.ObjectStorageService_GetObjectClient, error) {
	_ = "STUB: not implemented"
	return *new(s3.ObjectStorageService_GetObjectClient), nil
}

// GetObject indicates an expected call of GetObject.
func (mr *MockObjectStorageServiceClientMockRecorder) GetObject(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetObjectCannedAcl mocks base method.
func (m *MockObjectStorageServiceClient) GetObjectCannedAcl(ctx context.Context, in *s3.GetObjectCannedAclInput, opts ...grpc.CallOption) (*s3.GetObjectCannedAclOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetObjectCannedAcl indicates an expected call of GetObjectCannedAcl.
func (mr *MockObjectStorageServiceClientMockRecorder) GetObjectCannedAcl(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetObjectTagging mocks base method.
func (m *MockObjectStorageServiceClient) GetObjectTagging(ctx context.Context, in *s3.GetObjectTaggingInput, opts ...grpc.CallOption) (*s3.GetObjectTaggingOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetObjectTagging indicates an expected call of GetObjectTagging.
func (mr *MockObjectStorageServiceClientMockRecorder) GetObjectTagging(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// HeadObject mocks base method.
func (m *MockObjectStorageServiceClient) HeadObject(ctx context.Context, in *s3.HeadObjectInput, opts ...grpc.CallOption) (*s3.HeadObjectOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// HeadObject indicates an expected call of HeadObject.
func (mr *MockObjectStorageServiceClientMockRecorder) HeadObject(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// IsObjectExist mocks base method.
func (m *MockObjectStorageServiceClient) IsObjectExist(ctx context.Context, in *s3.IsObjectExistInput, opts ...grpc.CallOption) (*s3.IsObjectExistOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// IsObjectExist indicates an expected call of IsObjectExist.
func (mr *MockObjectStorageServiceClientMockRecorder) IsObjectExist(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ListMultipartUploads mocks base method.
func (m *MockObjectStorageServiceClient) ListMultipartUploads(ctx context.Context, in *s3.ListMultipartUploadsInput, opts ...grpc.CallOption) (*s3.ListMultipartUploadsOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListMultipartUploads indicates an expected call of ListMultipartUploads.
func (mr *MockObjectStorageServiceClientMockRecorder) ListMultipartUploads(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ListObjectVersions mocks base method.
func (m *MockObjectStorageServiceClient) ListObjectVersions(ctx context.Context, in *s3.ListObjectVersionsInput, opts ...grpc.CallOption) (*s3.ListObjectVersionsOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListObjectVersions indicates an expected call of ListObjectVersions.
func (mr *MockObjectStorageServiceClientMockRecorder) ListObjectVersions(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ListObjects mocks base method.
func (m *MockObjectStorageServiceClient) ListObjects(ctx context.Context, in *s3.ListObjectsInput, opts ...grpc.CallOption) (*s3.ListObjectsOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListObjects indicates an expected call of ListObjects.
func (mr *MockObjectStorageServiceClientMockRecorder) ListObjects(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ListParts mocks base method.
func (m *MockObjectStorageServiceClient) ListParts(ctx context.Context, in *s3.ListPartsInput, opts ...grpc.CallOption) (*s3.ListPartsOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListParts indicates an expected call of ListParts.
func (mr *MockObjectStorageServiceClientMockRecorder) ListParts(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// PutObject mocks base method.
func (m *MockObjectStorageServiceClient) PutObject(ctx context.Context, opts ...grpc.CallOption) (s3.ObjectStorageService_PutObjectClient, error) {
	_ = "STUB: not implemented"
	return *new(s3.ObjectStorageService_PutObjectClient), nil
}

// PutObject indicates an expected call of PutObject.
func (mr *MockObjectStorageServiceClientMockRecorder) PutObject(ctx interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// PutObjectCannedAcl mocks base method.
func (m *MockObjectStorageServiceClient) PutObjectCannedAcl(ctx context.Context, in *s3.PutObjectCannedAclInput, opts ...grpc.CallOption) (*s3.PutObjectCannedAclOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PutObjectCannedAcl indicates an expected call of PutObjectCannedAcl.
func (mr *MockObjectStorageServiceClientMockRecorder) PutObjectCannedAcl(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// PutObjectTagging mocks base method.
func (m *MockObjectStorageServiceClient) PutObjectTagging(ctx context.Context, in *s3.PutObjectTaggingInput, opts ...grpc.CallOption) (*s3.PutObjectTaggingOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PutObjectTagging indicates an expected call of PutObjectTagging.
func (mr *MockObjectStorageServiceClientMockRecorder) PutObjectTagging(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// RestoreObject mocks base method.
func (m *MockObjectStorageServiceClient) RestoreObject(ctx context.Context, in *s3.RestoreObjectInput, opts ...grpc.CallOption) (*s3.RestoreObjectOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// RestoreObject indicates an expected call of RestoreObject.
func (mr *MockObjectStorageServiceClientMockRecorder) RestoreObject(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SignURL mocks base method.
func (m *MockObjectStorageServiceClient) SignURL(ctx context.Context, in *s3.SignURLInput, opts ...grpc.CallOption) (*s3.SignURLOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// SignURL indicates an expected call of SignURL.
func (mr *MockObjectStorageServiceClientMockRecorder) SignURL(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// UpdateDownloadBandwidthRateLimit mocks base method.
func (m *MockObjectStorageServiceClient) UpdateDownloadBandwidthRateLimit(ctx context.Context, in *s3.UpdateBandwidthRateLimitInput, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UpdateDownloadBandwidthRateLimit indicates an expected call of UpdateDownloadBandwidthRateLimit.
func (mr *MockObjectStorageServiceClientMockRecorder) UpdateDownloadBandwidthRateLimit(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// UpdateUploadBandwidthRateLimit mocks base method.
func (m *MockObjectStorageServiceClient) UpdateUploadBandwidthRateLimit(ctx context.Context, in *s3.UpdateBandwidthRateLimitInput, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UpdateUploadBandwidthRateLimit indicates an expected call of UpdateUploadBandwidthRateLimit.
func (mr *MockObjectStorageServiceClientMockRecorder) UpdateUploadBandwidthRateLimit(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// UploadPart mocks base method.
func (m *MockObjectStorageServiceClient) UploadPart(ctx context.Context, opts ...grpc.CallOption) (s3.ObjectStorageService_UploadPartClient, error) {
	_ = "STUB: not implemented"
	return *new(s3.ObjectStorageService_UploadPartClient), nil
}

// UploadPart indicates an expected call of UploadPart.
func (mr *MockObjectStorageServiceClientMockRecorder) UploadPart(ctx interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// UploadPartCopy mocks base method.
func (m *MockObjectStorageServiceClient) UploadPartCopy(ctx context.Context, in *s3.UploadPartCopyInput, opts ...grpc.CallOption) (*s3.UploadPartCopyOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UploadPartCopy indicates an expected call of UploadPartCopy.
func (mr *MockObjectStorageServiceClientMockRecorder) UploadPartCopy(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockObjectStorageService_PutObjectClient is a mock of ObjectStorageService_PutObjectClient interface.
type MockObjectStorageService_PutObjectClient struct {
	ctrl     *gomock.Controller
	recorder *MockObjectStorageService_PutObjectClientMockRecorder
}

// MockObjectStorageService_PutObjectClientMockRecorder is the mock recorder for MockObjectStorageService_PutObjectClient.
type MockObjectStorageService_PutObjectClientMockRecorder struct {
	mock *MockObjectStorageService_PutObjectClient
}

// NewMockObjectStorageService_PutObjectClient creates a new mock instance.
func NewMockObjectStorageService_PutObjectClient(ctrl *gomock.Controller) *MockObjectStorageService_PutObjectClient {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockObjectStorageService_PutObjectClient) EXPECT() *MockObjectStorageService_PutObjectClientMockRecorder {
	_ = "STUB: not implemented"

	// CloseAndRecv mocks base method.
	return nil
}

func (m *MockObjectStorageService_PutObjectClient) CloseAndRecv() (*s3.PutObjectOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CloseAndRecv indicates an expected call of CloseAndRecv.
func (mr *MockObjectStorageService_PutObjectClientMockRecorder) CloseAndRecv() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// CloseSend mocks base method.
func (m *MockObjectStorageService_PutObjectClient) CloseSend() error {
	_ = "STUB: not implemented"
	return nil
}

// CloseSend indicates an expected call of CloseSend.
func (mr *MockObjectStorageService_PutObjectClientMockRecorder) CloseSend() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Context mocks base method.
func (m *MockObjectStorageService_PutObjectClient) Context() context.Context {
	_ = "STUB: not implemented"
	return *new(context.Context)
}

// Context indicates an expected call of Context.
func (mr *MockObjectStorageService_PutObjectClientMockRecorder) Context() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Header mocks base method.
func (m *MockObjectStorageService_PutObjectClient) Header() (metadata.MD, error) {
	_ = "STUB: not implemented"
	return *new(metadata.MD), nil
}

// Header indicates an expected call of Header.
func (mr *MockObjectStorageService_PutObjectClientMockRecorder) Header() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// RecvMsg mocks base method.
func (m_2 *MockObjectStorageService_PutObjectClient) RecvMsg(m interface{}) error {
	_ = "STUB: not implemented"
	return nil
}

// RecvMsg indicates an expected call of RecvMsg.
func (mr *MockObjectStorageService_PutObjectClientMockRecorder) RecvMsg(m interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Send mocks base method.
func (m *MockObjectStorageService_PutObjectClient) Send(arg0 *s3.PutObjectInput) error {
	_ = "STUB: not implemented"
	return nil
}

// Send indicates an expected call of Send.
func (mr *MockObjectStorageService_PutObjectClientMockRecorder) Send(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SendMsg mocks base method.
func (m_2 *MockObjectStorageService_PutObjectClient) SendMsg(m interface{}) error {
	_ = "STUB: not implemented"
	return nil
}

// SendMsg indicates an expected call of SendMsg.
func (mr *MockObjectStorageService_PutObjectClientMockRecorder) SendMsg(m interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Trailer mocks base method.
func (m *MockObjectStorageService_PutObjectClient) Trailer() metadata.MD {
	_ = "STUB: not implemented"
	return *new(metadata.MD)
}

// Trailer indicates an expected call of Trailer.
func (mr *MockObjectStorageService_PutObjectClientMockRecorder) Trailer() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockObjectStorageService_GetObjectClient is a mock of ObjectStorageService_GetObjectClient interface.
type MockObjectStorageService_GetObjectClient struct {
	ctrl     *gomock.Controller
	recorder *MockObjectStorageService_GetObjectClientMockRecorder
}

// MockObjectStorageService_GetObjectClientMockRecorder is the mock recorder for MockObjectStorageService_GetObjectClient.
type MockObjectStorageService_GetObjectClientMockRecorder struct {
	mock *MockObjectStorageService_GetObjectClient
}

// NewMockObjectStorageService_GetObjectClient creates a new mock instance.
func NewMockObjectStorageService_GetObjectClient(ctrl *gomock.Controller) *MockObjectStorageService_GetObjectClient {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockObjectStorageService_GetObjectClient) EXPECT() *MockObjectStorageService_GetObjectClientMockRecorder {
	_ = "STUB: not implemented"

	// CloseSend mocks base method.
	return nil
}

func (m *MockObjectStorageService_GetObjectClient) CloseSend() error {
	_ = "STUB: not implemented"
	return nil
}

// CloseSend indicates an expected call of CloseSend.
func (mr *MockObjectStorageService_GetObjectClientMockRecorder) CloseSend() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Context mocks base method.
func (m *MockObjectStorageService_GetObjectClient) Context() context.Context {
	_ = "STUB: not implemented"
	return *new(context.Context)
}

// Context indicates an expected call of Context.
func (mr *MockObjectStorageService_GetObjectClientMockRecorder) Context() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Header mocks base method.
func (m *MockObjectStorageService_GetObjectClient) Header() (metadata.MD, error) {
	_ = "STUB: not implemented"
	return *new(metadata.MD), nil
}

// Header indicates an expected call of Header.
func (mr *MockObjectStorageService_GetObjectClientMockRecorder) Header() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Recv mocks base method.
func (m *MockObjectStorageService_GetObjectClient) Recv() (*s3.GetObjectOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Recv indicates an expected call of Recv.
func (mr *MockObjectStorageService_GetObjectClientMockRecorder) Recv() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// RecvMsg mocks base method.
func (m_2 *MockObjectStorageService_GetObjectClient) RecvMsg(m interface{}) error {
	_ = "STUB: not implemented"
	return nil
}

// RecvMsg indicates an expected call of RecvMsg.
func (mr *MockObjectStorageService_GetObjectClientMockRecorder) RecvMsg(m interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SendMsg mocks base method.
func (m_2 *MockObjectStorageService_GetObjectClient) SendMsg(m interface{}) error {
	_ = "STUB: not implemented"
	return nil
}

// SendMsg indicates an expected call of SendMsg.
func (mr *MockObjectStorageService_GetObjectClientMockRecorder) SendMsg(m interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Trailer mocks base method.
func (m *MockObjectStorageService_GetObjectClient) Trailer() metadata.MD {
	_ = "STUB: not implemented"
	return *new(metadata.MD)
}

// Trailer indicates an expected call of Trailer.
func (mr *MockObjectStorageService_GetObjectClientMockRecorder) Trailer() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockObjectStorageService_UploadPartClient is a mock of ObjectStorageService_UploadPartClient interface.
type MockObjectStorageService_UploadPartClient struct {
	ctrl     *gomock.Controller
	recorder *MockObjectStorageService_UploadPartClientMockRecorder
}

// MockObjectStorageService_UploadPartClientMockRecorder is the mock recorder for MockObjectStorageService_UploadPartClient.
type MockObjectStorageService_UploadPartClientMockRecorder struct {
	mock *MockObjectStorageService_UploadPartClient
}

// NewMockObjectStorageService_UploadPartClient creates a new mock instance.
func NewMockObjectStorageService_UploadPartClient(ctrl *gomock.Controller) *MockObjectStorageService_UploadPartClient {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockObjectStorageService_UploadPartClient) EXPECT() *MockObjectStorageService_UploadPartClientMockRecorder {
	_ = "STUB: not implemented"

	// CloseAndRecv mocks base method.
	return nil
}

func (m *MockObjectStorageService_UploadPartClient) CloseAndRecv() (*s3.UploadPartOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CloseAndRecv indicates an expected call of CloseAndRecv.
func (mr *MockObjectStorageService_UploadPartClientMockRecorder) CloseAndRecv() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// CloseSend mocks base method.
func (m *MockObjectStorageService_UploadPartClient) CloseSend() error {
	_ = "STUB: not implemented"
	return nil
}

// CloseSend indicates an expected call of CloseSend.
func (mr *MockObjectStorageService_UploadPartClientMockRecorder) CloseSend() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Context mocks base method.
func (m *MockObjectStorageService_UploadPartClient) Context() context.Context {
	_ = "STUB: not implemented"
	return *new(context.Context)
}

// Context indicates an expected call of Context.
func (mr *MockObjectStorageService_UploadPartClientMockRecorder) Context() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Header mocks base method.
func (m *MockObjectStorageService_UploadPartClient) Header() (metadata.MD, error) {
	_ = "STUB: not implemented"
	return *new(metadata.MD), nil
}

// Header indicates an expected call of Header.
func (mr *MockObjectStorageService_UploadPartClientMockRecorder) Header() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// RecvMsg mocks base method.
func (m_2 *MockObjectStorageService_UploadPartClient) RecvMsg(m interface{}) error {
	_ = "STUB: not implemented"
	return nil
}

// RecvMsg indicates an expected call of RecvMsg.
func (mr *MockObjectStorageService_UploadPartClientMockRecorder) RecvMsg(m interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Send mocks base method.
func (m *MockObjectStorageService_UploadPartClient) Send(arg0 *s3.UploadPartInput) error {
	_ = "STUB: not implemented"
	return nil
}

// Send indicates an expected call of Send.
func (mr *MockObjectStorageService_UploadPartClientMockRecorder) Send(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SendMsg mocks base method.
func (m_2 *MockObjectStorageService_UploadPartClient) SendMsg(m interface{}) error {
	_ = "STUB: not implemented"
	return nil
}

// SendMsg indicates an expected call of SendMsg.
func (mr *MockObjectStorageService_UploadPartClientMockRecorder) SendMsg(m interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Trailer mocks base method.
func (m *MockObjectStorageService_UploadPartClient) Trailer() metadata.MD {
	_ = "STUB: not implemented"
	return *new(metadata.MD)
}

// Trailer indicates an expected call of Trailer.
func (mr *MockObjectStorageService_UploadPartClientMockRecorder) Trailer() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockObjectStorageService_AppendObjectClient is a mock of ObjectStorageService_AppendObjectClient interface.
type MockObjectStorageService_AppendObjectClient struct {
	ctrl     *gomock.Controller
	recorder *MockObjectStorageService_AppendObjectClientMockRecorder
}

// MockObjectStorageService_AppendObjectClientMockRecorder is the mock recorder for MockObjectStorageService_AppendObjectClient.
type MockObjectStorageService_AppendObjectClientMockRecorder struct {
	mock *MockObjectStorageService_AppendObjectClient
}

// NewMockObjectStorageService_AppendObjectClient creates a new mock instance.
func NewMockObjectStorageService_AppendObjectClient(ctrl *gomock.Controller) *MockObjectStorageService_AppendObjectClient {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockObjectStorageService_AppendObjectClient) EXPECT() *MockObjectStorageService_AppendObjectClientMockRecorder {
	_ = "STUB: not implemented"

	// CloseAndRecv mocks base method.
	return nil
}

func (m *MockObjectStorageService_AppendObjectClient) CloseAndRecv() (*s3.AppendObjectOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CloseAndRecv indicates an expected call of CloseAndRecv.
func (mr *MockObjectStorageService_AppendObjectClientMockRecorder) CloseAndRecv() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// CloseSend mocks base method.
func (m *MockObjectStorageService_AppendObjectClient) CloseSend() error {
	_ = "STUB: not implemented"
	return nil
}

// CloseSend indicates an expected call of CloseSend.
func (mr *MockObjectStorageService_AppendObjectClientMockRecorder) CloseSend() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Context mocks base method.
func (m *MockObjectStorageService_AppendObjectClient) Context() context.Context {
	_ = "STUB: not implemented"
	return *new(context.Context)
}

// Context indicates an expected call of Context.
func (mr *MockObjectStorageService_AppendObjectClientMockRecorder) Context() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Header mocks base method.
func (m *MockObjectStorageService_AppendObjectClient) Header() (metadata.MD, error) {
	_ = "STUB: not implemented"
	return *new(metadata.MD), nil
}

// Header indicates an expected call of Header.
func (mr *MockObjectStorageService_AppendObjectClientMockRecorder) Header() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// RecvMsg mocks base method.
func (m_2 *MockObjectStorageService_AppendObjectClient) RecvMsg(m interface{}) error {
	_ = "STUB: not implemented"
	return nil
}

// RecvMsg indicates an expected call of RecvMsg.
func (mr *MockObjectStorageService_AppendObjectClientMockRecorder) RecvMsg(m interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Send mocks base method.
func (m *MockObjectStorageService_AppendObjectClient) Send(arg0 *s3.AppendObjectInput) error {
	_ = "STUB: not implemented"
	return nil
}

// Send indicates an expected call of Send.
func (mr *MockObjectStorageService_AppendObjectClientMockRecorder) Send(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SendMsg mocks base method.
func (m_2 *MockObjectStorageService_AppendObjectClient) SendMsg(m interface{}) error {
	_ = "STUB: not implemented"
	return nil
}

// SendMsg indicates an expected call of SendMsg.
func (mr *MockObjectStorageService_AppendObjectClientMockRecorder) SendMsg(m interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Trailer mocks base method.
func (m *MockObjectStorageService_AppendObjectClient) Trailer() metadata.MD {
	_ = "STUB: not implemented"
	return *new(metadata.MD)
}

// Trailer indicates an expected call of Trailer.
func (mr *MockObjectStorageService_AppendObjectClientMockRecorder) Trailer() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockObjectStorageServiceServer is a mock of ObjectStorageServiceServer interface.
type MockObjectStorageServiceServer struct {
	ctrl     *gomock.Controller
	recorder *MockObjectStorageServiceServerMockRecorder
}

// MockObjectStorageServiceServerMockRecorder is the mock recorder for MockObjectStorageServiceServer.
type MockObjectStorageServiceServerMockRecorder struct {
	mock *MockObjectStorageServiceServer
}

// NewMockObjectStorageServiceServer creates a new mock instance.
func NewMockObjectStorageServiceServer(ctrl *gomock.Controller) *MockObjectStorageServiceServer {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockObjectStorageServiceServer) EXPECT() *MockObjectStorageServiceServerMockRecorder {
	_ = "STUB: not implemented"

	// AbortMultipartUpload mocks base method.
	return nil
}

func (m *MockObjectStorageServiceServer) AbortMultipartUpload(arg0 context.Context, arg1 *s3.AbortMultipartUploadInput) (*s3.AbortMultipartUploadOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// AbortMultipartUpload indicates an expected call of AbortMultipartUpload.
func (mr *MockObjectStorageServiceServerMockRecorder) AbortMultipartUpload(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// AppendObject mocks base method.
func (m *MockObjectStorageServiceServer) AppendObject(arg0 s3.ObjectStorageService_AppendObjectServer) error {
	_ = "STUB: not implemented"
	return nil
}

// AppendObject indicates an expected call of AppendObject.
func (mr *MockObjectStorageServiceServerMockRecorder) AppendObject(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// CompleteMultipartUpload mocks base method.
func (m *MockObjectStorageServiceServer) CompleteMultipartUpload(arg0 context.Context, arg1 *s3.CompleteMultipartUploadInput) (*s3.CompleteMultipartUploadOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CompleteMultipartUpload indicates an expected call of CompleteMultipartUpload.
func (mr *MockObjectStorageServiceServerMockRecorder) CompleteMultipartUpload(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// CopyObject mocks base method.
func (m *MockObjectStorageServiceServer) CopyObject(arg0 context.Context, arg1 *s3.CopyObjectInput) (*s3.CopyObjectOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CopyObject indicates an expected call of CopyObject.
func (mr *MockObjectStorageServiceServerMockRecorder) CopyObject(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// CreateMultipartUpload mocks base method.
func (m *MockObjectStorageServiceServer) CreateMultipartUpload(arg0 context.Context, arg1 *s3.CreateMultipartUploadInput) (*s3.CreateMultipartUploadOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateMultipartUpload indicates an expected call of CreateMultipartUpload.
func (mr *MockObjectStorageServiceServerMockRecorder) CreateMultipartUpload(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// DeleteObject mocks base method.
func (m *MockObjectStorageServiceServer) DeleteObject(arg0 context.Context, arg1 *s3.DeleteObjectInput) (*s3.DeleteObjectOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteObject indicates an expected call of DeleteObject.
func (mr *MockObjectStorageServiceServerMockRecorder) DeleteObject(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// DeleteObjectTagging mocks base method.
func (m *MockObjectStorageServiceServer) DeleteObjectTagging(arg0 context.Context, arg1 *s3.DeleteObjectTaggingInput) (*s3.DeleteObjectTaggingOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteObjectTagging indicates an expected call of DeleteObjectTagging.
func (mr *MockObjectStorageServiceServerMockRecorder) DeleteObjectTagging(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// DeleteObjects mocks base method.
func (m *MockObjectStorageServiceServer) DeleteObjects(arg0 context.Context, arg1 *s3.DeleteObjectsInput) (*s3.DeleteObjectsOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteObjects indicates an expected call of DeleteObjects.
func (mr *MockObjectStorageServiceServerMockRecorder) DeleteObjects(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetObject mocks base method.
func (m *MockObjectStorageServiceServer) GetObject(arg0 *s3.GetObjectInput, arg1 s3.ObjectStorageService_GetObjectServer) error {
	_ = "STUB: not implemented"
	return nil
}

// GetObject indicates an expected call of GetObject.
func (mr *MockObjectStorageServiceServerMockRecorder) GetObject(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetObjectCannedAcl mocks base method.
func (m *MockObjectStorageServiceServer) GetObjectCannedAcl(arg0 context.Context, arg1 *s3.GetObjectCannedAclInput) (*s3.GetObjectCannedAclOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetObjectCannedAcl indicates an expected call of GetObjectCannedAcl.
func (mr *MockObjectStorageServiceServerMockRecorder) GetObjectCannedAcl(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetObjectTagging mocks base method.
func (m *MockObjectStorageServiceServer) GetObjectTagging(arg0 context.Context, arg1 *s3.GetObjectTaggingInput) (*s3.GetObjectTaggingOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetObjectTagging indicates an expected call of GetObjectTagging.
func (mr *MockObjectStorageServiceServerMockRecorder) GetObjectTagging(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// HeadObject mocks base method.
func (m *MockObjectStorageServiceServer) HeadObject(arg0 context.Context, arg1 *s3.HeadObjectInput) (*s3.HeadObjectOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// HeadObject indicates an expected call of HeadObject.
func (mr *MockObjectStorageServiceServerMockRecorder) HeadObject(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// IsObjectExist mocks base method.
func (m *MockObjectStorageServiceServer) IsObjectExist(arg0 context.Context, arg1 *s3.IsObjectExistInput) (*s3.IsObjectExistOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// IsObjectExist indicates an expected call of IsObjectExist.
func (mr *MockObjectStorageServiceServerMockRecorder) IsObjectExist(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ListMultipartUploads mocks base method.
func (m *MockObjectStorageServiceServer) ListMultipartUploads(arg0 context.Context, arg1 *s3.ListMultipartUploadsInput) (*s3.ListMultipartUploadsOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListMultipartUploads indicates an expected call of ListMultipartUploads.
func (mr *MockObjectStorageServiceServerMockRecorder) ListMultipartUploads(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ListObjectVersions mocks base method.
func (m *MockObjectStorageServiceServer) ListObjectVersions(arg0 context.Context, arg1 *s3.ListObjectVersionsInput) (*s3.ListObjectVersionsOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListObjectVersions indicates an expected call of ListObjectVersions.
func (mr *MockObjectStorageServiceServerMockRecorder) ListObjectVersions(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ListObjects mocks base method.
func (m *MockObjectStorageServiceServer) ListObjects(arg0 context.Context, arg1 *s3.ListObjectsInput) (*s3.ListObjectsOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListObjects indicates an expected call of ListObjects.
func (mr *MockObjectStorageServiceServerMockRecorder) ListObjects(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ListParts mocks base method.
func (m *MockObjectStorageServiceServer) ListParts(arg0 context.Context, arg1 *s3.ListPartsInput) (*s3.ListPartsOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListParts indicates an expected call of ListParts.
func (mr *MockObjectStorageServiceServerMockRecorder) ListParts(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// PutObject mocks base method.
func (m *MockObjectStorageServiceServer) PutObject(arg0 s3.ObjectStorageService_PutObjectServer) error {
	_ = "STUB: not implemented"
	return nil
}

// PutObject indicates an expected call of PutObject.
func (mr *MockObjectStorageServiceServerMockRecorder) PutObject(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// PutObjectCannedAcl mocks base method.
func (m *MockObjectStorageServiceServer) PutObjectCannedAcl(arg0 context.Context, arg1 *s3.PutObjectCannedAclInput) (*s3.PutObjectCannedAclOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PutObjectCannedAcl indicates an expected call of PutObjectCannedAcl.
func (mr *MockObjectStorageServiceServerMockRecorder) PutObjectCannedAcl(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// PutObjectTagging mocks base method.
func (m *MockObjectStorageServiceServer) PutObjectTagging(arg0 context.Context, arg1 *s3.PutObjectTaggingInput) (*s3.PutObjectTaggingOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PutObjectTagging indicates an expected call of PutObjectTagging.
func (mr *MockObjectStorageServiceServerMockRecorder) PutObjectTagging(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// RestoreObject mocks base method.
func (m *MockObjectStorageServiceServer) RestoreObject(arg0 context.Context, arg1 *s3.RestoreObjectInput) (*s3.RestoreObjectOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// RestoreObject indicates an expected call of RestoreObject.
func (mr *MockObjectStorageServiceServerMockRecorder) RestoreObject(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SignURL mocks base method.
func (m *MockObjectStorageServiceServer) SignURL(arg0 context.Context, arg1 *s3.SignURLInput) (*s3.SignURLOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// SignURL indicates an expected call of SignURL.
func (mr *MockObjectStorageServiceServerMockRecorder) SignURL(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// UpdateDownloadBandwidthRateLimit mocks base method.
func (m *MockObjectStorageServiceServer) UpdateDownloadBandwidthRateLimit(arg0 context.Context, arg1 *s3.UpdateBandwidthRateLimitInput) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UpdateDownloadBandwidthRateLimit indicates an expected call of UpdateDownloadBandwidthRateLimit.
func (mr *MockObjectStorageServiceServerMockRecorder) UpdateDownloadBandwidthRateLimit(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// UpdateUploadBandwidthRateLimit mocks base method.
func (m *MockObjectStorageServiceServer) UpdateUploadBandwidthRateLimit(arg0 context.Context, arg1 *s3.UpdateBandwidthRateLimitInput) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UpdateUploadBandwidthRateLimit indicates an expected call of UpdateUploadBandwidthRateLimit.
func (mr *MockObjectStorageServiceServerMockRecorder) UpdateUploadBandwidthRateLimit(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// UploadPart mocks base method.
func (m *MockObjectStorageServiceServer) UploadPart(arg0 s3.ObjectStorageService_UploadPartServer) error {
	_ = "STUB: not implemented"
	return nil
}

// UploadPart indicates an expected call of UploadPart.
func (mr *MockObjectStorageServiceServerMockRecorder) UploadPart(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// UploadPartCopy mocks base method.
func (m *MockObjectStorageServiceServer) UploadPartCopy(arg0 context.Context, arg1 *s3.UploadPartCopyInput) (*s3.UploadPartCopyOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UploadPartCopy indicates an expected call of UploadPartCopy.
func (mr *MockObjectStorageServiceServerMockRecorder) UploadPartCopy(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockUnsafeObjectStorageServiceServer is a mock of UnsafeObjectStorageServiceServer interface.
type MockUnsafeObjectStorageServiceServer struct {
	ctrl     *gomock.Controller
	recorder *MockUnsafeObjectStorageServiceServerMockRecorder
}

// MockUnsafeObjectStorageServiceServerMockRecorder is the mock recorder for MockUnsafeObjectStorageServiceServer.
type MockUnsafeObjectStorageServiceServerMockRecorder struct {
	mock *MockUnsafeObjectStorageServiceServer
}

// NewMockUnsafeObjectStorageServiceServer creates a new mock instance.
func NewMockUnsafeObjectStorageServiceServer(ctrl *gomock.Controller) *MockUnsafeObjectStorageServiceServer {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUnsafeObjectStorageServiceServer) EXPECT() *MockUnsafeObjectStorageServiceServerMockRecorder {
	_ = "STUB: not implemented"

	// mustEmbedUnimplementedObjectStorageServiceServer mocks base method.
	return nil
}

func (m *MockUnsafeObjectStorageServiceServer) mustEmbedUnimplementedObjectStorageServiceServer() {
	_ = "STUB: not implemented"
	return
}

// mustEmbedUnimplementedObjectStorageServiceServer indicates an expected call of mustEmbedUnimplementedObjectStorageServiceServer.
func (mr *MockUnsafeObjectStorageServiceServerMockRecorder) mustEmbedUnimplementedObjectStorageServiceServer() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockObjectStorageService_PutObjectServer is a mock of ObjectStorageService_PutObjectServer interface.
type MockObjectStorageService_PutObjectServer struct {
	ctrl     *gomock.Controller
	recorder *MockObjectStorageService_PutObjectServerMockRecorder
}

// MockObjectStorageService_PutObjectServerMockRecorder is the mock recorder for MockObjectStorageService_PutObjectServer.
type MockObjectStorageService_PutObjectServerMockRecorder struct {
	mock *MockObjectStorageService_PutObjectServer
}

// NewMockObjectStorageService_PutObjectServer creates a new mock instance.
func NewMockObjectStorageService_PutObjectServer(ctrl *gomock.Controller) *MockObjectStorageService_PutObjectServer {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockObjectStorageService_PutObjectServer) EXPECT() *MockObjectStorageService_PutObjectServerMockRecorder {
	_ = "STUB: not implemented"

	// Context mocks base method.
	return nil
}

func (m *MockObjectStorageService_PutObjectServer) Context() context.Context {
	_ = "STUB: not implemented"
	return *new(context.Context)
}

// Context indicates an expected call of Context.
func (mr *MockObjectStorageService_PutObjectServerMockRecorder) Context() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Recv mocks base method.
func (m *MockObjectStorageService_PutObjectServer) Recv() (*s3.PutObjectInput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Recv indicates an expected call of Recv.
func (mr *MockObjectStorageService_PutObjectServerMockRecorder) Recv() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// RecvMsg mocks base method.
func (m_2 *MockObjectStorageService_PutObjectServer) RecvMsg(m interface{}) error {
	_ = "STUB: not implemented"
	return nil
}

// RecvMsg indicates an expected call of RecvMsg.
func (mr *MockObjectStorageService_PutObjectServerMockRecorder) RecvMsg(m interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SendAndClose mocks base method.
func (m *MockObjectStorageService_PutObjectServer) SendAndClose(arg0 *s3.PutObjectOutput) error {
	_ = "STUB: not implemented"
	return nil
}

// SendAndClose indicates an expected call of SendAndClose.
func (mr *MockObjectStorageService_PutObjectServerMockRecorder) SendAndClose(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SendHeader mocks base method.
func (m *MockObjectStorageService_PutObjectServer) SendHeader(arg0 metadata.MD) error {
	_ = "STUB: not implemented"
	return nil
}

// SendHeader indicates an expected call of SendHeader.
func (mr *MockObjectStorageService_PutObjectServerMockRecorder) SendHeader(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SendMsg mocks base method.
func (m_2 *MockObjectStorageService_PutObjectServer) SendMsg(m interface{}) error {
	_ = "STUB: not implemented"
	return nil
}

// SendMsg indicates an expected call of SendMsg.
func (mr *MockObjectStorageService_PutObjectServerMockRecorder) SendMsg(m interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetHeader mocks base method.
func (m *MockObjectStorageService_PutObjectServer) SetHeader(arg0 metadata.MD) error {
	_ = "STUB: not implemented"
	return nil
}

// SetHeader indicates an expected call of SetHeader.
func (mr *MockObjectStorageService_PutObjectServerMockRecorder) SetHeader(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetTrailer mocks base method.
func (m *MockObjectStorageService_PutObjectServer) SetTrailer(arg0 metadata.MD) {
	_ = "STUB: not implemented"
	return
}

// SetTrailer indicates an expected call of SetTrailer.
func (mr *MockObjectStorageService_PutObjectServerMockRecorder) SetTrailer(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockObjectStorageService_GetObjectServer is a mock of ObjectStorageService_GetObjectServer interface.
type MockObjectStorageService_GetObjectServer struct {
	ctrl     *gomock.Controller
	recorder *MockObjectStorageService_GetObjectServerMockRecorder
}

// MockObjectStorageService_GetObjectServerMockRecorder is the mock recorder for MockObjectStorageService_GetObjectServer.
type MockObjectStorageService_GetObjectServerMockRecorder struct {
	mock *MockObjectStorageService_GetObjectServer
}

// NewMockObjectStorageService_GetObjectServer creates a new mock instance.
func NewMockObjectStorageService_GetObjectServer(ctrl *gomock.Controller) *MockObjectStorageService_GetObjectServer {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockObjectStorageService_GetObjectServer) EXPECT() *MockObjectStorageService_GetObjectServerMockRecorder {
	_ = "STUB: not implemented"

	// Context mocks base method.
	return nil
}

func (m *MockObjectStorageService_GetObjectServer) Context() context.Context {
	_ = "STUB: not implemented"
	return *new(context.Context)
}

// Context indicates an expected call of Context.
func (mr *MockObjectStorageService_GetObjectServerMockRecorder) Context() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// RecvMsg mocks base method.
func (m_2 *MockObjectStorageService_GetObjectServer) RecvMsg(m interface{}) error {
	_ = "STUB: not implemented"
	return nil
}

// RecvMsg indicates an expected call of RecvMsg.
func (mr *MockObjectStorageService_GetObjectServerMockRecorder) RecvMsg(m interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Send mocks base method.
func (m *MockObjectStorageService_GetObjectServer) Send(arg0 *s3.GetObjectOutput) error {
	_ = "STUB: not implemented"
	return nil
}

// Send indicates an expected call of Send.
func (mr *MockObjectStorageService_GetObjectServerMockRecorder) Send(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SendHeader mocks base method.
func (m *MockObjectStorageService_GetObjectServer) SendHeader(arg0 metadata.MD) error {
	_ = "STUB: not implemented"
	return nil
}

// SendHeader indicates an expected call of SendHeader.
func (mr *MockObjectStorageService_GetObjectServerMockRecorder) SendHeader(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SendMsg mocks base method.
func (m_2 *MockObjectStorageService_GetObjectServer) SendMsg(m interface{}) error {
	_ = "STUB: not implemented"
	return nil
}

// SendMsg indicates an expected call of SendMsg.
func (mr *MockObjectStorageService_GetObjectServerMockRecorder) SendMsg(m interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetHeader mocks base method.
func (m *MockObjectStorageService_GetObjectServer) SetHeader(arg0 metadata.MD) error {
	_ = "STUB: not implemented"
	return nil
}

// SetHeader indicates an expected call of SetHeader.
func (mr *MockObjectStorageService_GetObjectServerMockRecorder) SetHeader(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetTrailer mocks base method.
func (m *MockObjectStorageService_GetObjectServer) SetTrailer(arg0 metadata.MD) {
	_ = "STUB: not implemented"
	return
}

// SetTrailer indicates an expected call of SetTrailer.
func (mr *MockObjectStorageService_GetObjectServerMockRecorder) SetTrailer(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockObjectStorageService_UploadPartServer is a mock of ObjectStorageService_UploadPartServer interface.
type MockObjectStorageService_UploadPartServer struct {
	ctrl     *gomock.Controller
	recorder *MockObjectStorageService_UploadPartServerMockRecorder
}

// MockObjectStorageService_UploadPartServerMockRecorder is the mock recorder for MockObjectStorageService_UploadPartServer.
type MockObjectStorageService_UploadPartServerMockRecorder struct {
	mock *MockObjectStorageService_UploadPartServer
}

// NewMockObjectStorageService_UploadPartServer creates a new mock instance.
func NewMockObjectStorageService_UploadPartServer(ctrl *gomock.Controller) *MockObjectStorageService_UploadPartServer {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockObjectStorageService_UploadPartServer) EXPECT() *MockObjectStorageService_UploadPartServerMockRecorder {
	_ = "STUB: not implemented"

	// Context mocks base method.
	return nil
}

func (m *MockObjectStorageService_UploadPartServer) Context() context.Context {
	_ = "STUB: not implemented"
	return *new(context.Context)
}

// Context indicates an expected call of Context.
func (mr *MockObjectStorageService_UploadPartServerMockRecorder) Context() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Recv mocks base method.
func (m *MockObjectStorageService_UploadPartServer) Recv() (*s3.UploadPartInput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Recv indicates an expected call of Recv.
func (mr *MockObjectStorageService_UploadPartServerMockRecorder) Recv() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// RecvMsg mocks base method.
func (m_2 *MockObjectStorageService_UploadPartServer) RecvMsg(m interface{}) error {
	_ = "STUB: not implemented"
	return nil
}

// RecvMsg indicates an expected call of RecvMsg.
func (mr *MockObjectStorageService_UploadPartServerMockRecorder) RecvMsg(m interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SendAndClose mocks base method.
func (m *MockObjectStorageService_UploadPartServer) SendAndClose(arg0 *s3.UploadPartOutput) error {
	_ = "STUB: not implemented"
	return nil
}

// SendAndClose indicates an expected call of SendAndClose.
func (mr *MockObjectStorageService_UploadPartServerMockRecorder) SendAndClose(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SendHeader mocks base method.
func (m *MockObjectStorageService_UploadPartServer) SendHeader(arg0 metadata.MD) error {
	_ = "STUB: not implemented"
	return nil
}

// SendHeader indicates an expected call of SendHeader.
func (mr *MockObjectStorageService_UploadPartServerMockRecorder) SendHeader(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SendMsg mocks base method.
func (m_2 *MockObjectStorageService_UploadPartServer) SendMsg(m interface{}) error {
	_ = "STUB: not implemented"
	return nil
}

// SendMsg indicates an expected call of SendMsg.
func (mr *MockObjectStorageService_UploadPartServerMockRecorder) SendMsg(m interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetHeader mocks base method.
func (m *MockObjectStorageService_UploadPartServer) SetHeader(arg0 metadata.MD) error {
	_ = "STUB: not implemented"
	return nil
}

// SetHeader indicates an expected call of SetHeader.
func (mr *MockObjectStorageService_UploadPartServerMockRecorder) SetHeader(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetTrailer mocks base method.
func (m *MockObjectStorageService_UploadPartServer) SetTrailer(arg0 metadata.MD) {
	_ = "STUB: not implemented"
	return
}

// SetTrailer indicates an expected call of SetTrailer.
func (mr *MockObjectStorageService_UploadPartServerMockRecorder) SetTrailer(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockObjectStorageService_AppendObjectServer is a mock of ObjectStorageService_AppendObjectServer interface.
type MockObjectStorageService_AppendObjectServer struct {
	ctrl     *gomock.Controller
	recorder *MockObjectStorageService_AppendObjectServerMockRecorder
}

// MockObjectStorageService_AppendObjectServerMockRecorder is the mock recorder for MockObjectStorageService_AppendObjectServer.
type MockObjectStorageService_AppendObjectServerMockRecorder struct {
	mock *MockObjectStorageService_AppendObjectServer
}

// NewMockObjectStorageService_AppendObjectServer creates a new mock instance.
func NewMockObjectStorageService_AppendObjectServer(ctrl *gomock.Controller) *MockObjectStorageService_AppendObjectServer {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockObjectStorageService_AppendObjectServer) EXPECT() *MockObjectStorageService_AppendObjectServerMockRecorder {
	_ = "STUB: not implemented"

	// Context mocks base method.
	return nil
}

func (m *MockObjectStorageService_AppendObjectServer) Context() context.Context {
	_ = "STUB: not implemented"
	return *new(context.Context)
}

// Context indicates an expected call of Context.
func (mr *MockObjectStorageService_AppendObjectServerMockRecorder) Context() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Recv mocks base method.
func (m *MockObjectStorageService_AppendObjectServer) Recv() (*s3.AppendObjectInput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Recv indicates an expected call of Recv.
func (mr *MockObjectStorageService_AppendObjectServerMockRecorder) Recv() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// RecvMsg mocks base method.
func (m_2 *MockObjectStorageService_AppendObjectServer) RecvMsg(m interface{}) error {
	_ = "STUB: not implemented"
	return nil
}

// RecvMsg indicates an expected call of RecvMsg.
func (mr *MockObjectStorageService_AppendObjectServerMockRecorder) RecvMsg(m interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SendAndClose mocks base method.
func (m *MockObjectStorageService_AppendObjectServer) SendAndClose(arg0 *s3.AppendObjectOutput) error {
	_ = "STUB: not implemented"
	return nil
}

// SendAndClose indicates an expected call of SendAndClose.
func (mr *MockObjectStorageService_AppendObjectServerMockRecorder) SendAndClose(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SendHeader mocks base method.
func (m *MockObjectStorageService_AppendObjectServer) SendHeader(arg0 metadata.MD) error {
	_ = "STUB: not implemented"
	return nil
}

// SendHeader indicates an expected call of SendHeader.
func (mr *MockObjectStorageService_AppendObjectServerMockRecorder) SendHeader(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SendMsg mocks base method.
func (m_2 *MockObjectStorageService_AppendObjectServer) SendMsg(m interface{}) error {
	_ = "STUB: not implemented"
	return nil
}

// SendMsg indicates an expected call of SendMsg.
func (mr *MockObjectStorageService_AppendObjectServerMockRecorder) SendMsg(m interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetHeader mocks base method.
func (m *MockObjectStorageService_AppendObjectServer) SetHeader(arg0 metadata.MD) error {
	_ = "STUB: not implemented"
	return nil
}

// SetHeader indicates an expected call of SetHeader.
func (mr *MockObjectStorageService_AppendObjectServerMockRecorder) SetHeader(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetTrailer mocks base method.
func (m *MockObjectStorageService_AppendObjectServer) SetTrailer(arg0 metadata.MD) {
	_ = "STUB: not implemented"
	return
}

// SetTrailer indicates an expected call of SetTrailer.
func (mr *MockObjectStorageService_AppendObjectServerMockRecorder) SetTrailer(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
