// Code generated by MockGen. DO NOT EDIT.
// Source: components/sequencer/store.go

// Package mock_sequencer is a generated GoMock package.
package mock_sequencer

import (
	gomock "github.com/golang/mock/gomock"

	sequencer "mosn.io/layotto/components/sequencer"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	_ = "STUB: not implemented"

	// GetNextId mocks base method.
	return nil
}

func (m *MockStore) GetNextId(arg0 *sequencer.GetNextIdRequest) (*sequencer.GetNextIdResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetNextId indicates an expected call of GetNextId.
func (mr *MockStoreMockRecorder) GetNextId(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetSegment mocks base method.
func (m *MockStore) GetSegment(arg0 *sequencer.GetSegmentRequest) (bool, *sequencer.GetSegmentResponse, error) {
	_ = "STUB: not implemented"
	return false, nil, nil
}

// GetSegment indicates an expected call of GetSegment.
func (mr *MockStoreMockRecorder) GetSegment(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Init mocks base method.
func (m *MockStore) Init(config sequencer.Configuration) error {
	_ = "STUB: not implemented"
	return nil
}

// Init indicates an expected call of Init.
func (mr *MockStoreMockRecorder) Init(config interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
