// Code generated by MockGen. DO NOT EDIT.
// Source: spec/proto/runtime/v1/appcallback.pb.go

// Package mock_appcallback is a generated GoMock package.
package mock_appcallback

import (
	context "context"

	gomock "github.com/golang/mock/gomock"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"

	runtime "mosn.io/layotto/spec/proto/runtime/v1"
)

// MockAppCallbackClient is a mock of AppCallbackClient interface.
type MockAppCallbackClient struct {
	ctrl     *gomock.Controller
	recorder *MockAppCallbackClientMockRecorder
}

// MockAppCallbackClientMockRecorder is the mock recorder for MockAppCallbackClient.
type MockAppCallbackClientMockRecorder struct {
	mock *MockAppCallbackClient
}

// NewMockAppCallbackClient creates a new mock instance.
func NewMockAppCallbackClient(ctrl *gomock.Controller) *MockAppCallbackClient {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAppCallbackClient) EXPECT() *MockAppCallbackClientMockRecorder {
	_ = "STUB: not implemented"

	// ListTopicSubscriptions mocks base method.
	return nil
}

func (m *MockAppCallbackClient) ListTopicSubscriptions(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*runtime.ListTopicSubscriptionsResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListTopicSubscriptions indicates an expected call of ListTopicSubscriptions.
func (mr *MockAppCallbackClientMockRecorder) ListTopicSubscriptions(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// OnTopicEvent mocks base method.
func (m *MockAppCallbackClient) OnTopicEvent(ctx context.Context, in *runtime.TopicEventRequest, opts ...grpc.CallOption) (*runtime.TopicEventResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// OnTopicEvent indicates an expected call of OnTopicEvent.
func (mr *MockAppCallbackClientMockRecorder) OnTopicEvent(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockAppCallbackServer is a mock of AppCallbackServer interface.
type MockAppCallbackServer struct {
	ctrl     *gomock.Controller
	recorder *MockAppCallbackServerMockRecorder
}

// MockAppCallbackServerMockRecorder is the mock recorder for MockAppCallbackServer.
type MockAppCallbackServerMockRecorder struct {
	mock *MockAppCallbackServer
}

// NewMockAppCallbackServer creates a new mock instance.
func NewMockAppCallbackServer(ctrl *gomock.Controller) *MockAppCallbackServer {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAppCallbackServer) EXPECT() *MockAppCallbackServerMockRecorder {
	_ = "STUB: not implemented"

	// ListTopicSubscriptions mocks base method.
	return nil
}

func (m *MockAppCallbackServer) ListTopicSubscriptions(arg0 context.Context, arg1 *empty.Empty) (*runtime.ListTopicSubscriptionsResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListTopicSubscriptions indicates an expected call of ListTopicSubscriptions.
func (mr *MockAppCallbackServerMockRecorder) ListTopicSubscriptions(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// OnTopicEvent mocks base method.
func (m *MockAppCallbackServer) OnTopicEvent(arg0 context.Context, arg1 *runtime.TopicEventRequest) (*runtime.TopicEventResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// OnTopicEvent indicates an expected call of OnTopicEvent.
func (mr *MockAppCallbackServerMockRecorder) OnTopicEvent(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
