// Code generated by github.com/seeflood/protoc-gen-p6. DO NOT EDIT.

// Copyright 2021 Layotto Authors
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package cryption

import (
	"context"

	cryption "mosn.io/layotto/components/cryption"
	cryption1 "mosn.io/layotto/spec/proto/extension/v1/cryption"

	rawGRPC "google.golang.org/grpc"

	grpc_api "mosn.io/layotto/pkg/grpc"
)

func NewAPI(ac *grpc_api.ApplicationContext) grpc_api.GrpcAPI {
	_ = "STUB: not implemented"
	return *new(grpc_api.GrpcAPI)
}

type server struct {
	appId      string
	components map[string]cryption.CryptionService
}

func (s *server) Decrypt(ctx context.Context, in *cryption1.DecryptRequest) (*cryption1.DecryptResponse, error) {
	_ = "STUB: not implemented"
	// find the component
	return nil, nil
}

// convert request

// delegate to the component

// convert response

func (s *server) Encrypt(ctx context.Context, in *cryption1.EncryptRequest) (*cryption1.EncryptResponse, error) {
	_ = "STUB: not implemented"
	// find the component
	return nil, nil
}

// convert request

// delegate to the component

// convert response

func invalidArgumentError(method string, format string, a ...interface{}) error {
	_ = "STUB: not implemented"
	return nil
}

func (s *server) Init(conn *rawGRPC.ClientConn) error { _ = "STUB: not implemented"; return nil }

func (s *server) Register(rawGrpcServer *rawGRPC.Server) error {
	_ = "STUB: not implemented"
	return nil
}
