// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/dapr/components-contrib/pubsub (interfaces: PubSub)

// Package mock is a generated GoMock package.
package mock

import (
	pubsub "github.com/dapr/components-contrib/pubsub"
	gomock "github.com/golang/mock/gomock"
)

// MockPubSub is a mock of PubSub interface.
type MockPubSub struct {
	ctrl     *gomock.Controller
	recorder *MockPubSubMockRecorder
}

// MockPubSubMockRecorder is the mock recorder for MockPubSub.
type MockPubSubMockRecorder struct {
	mock *MockPubSub
}

// NewMockPubSub creates a new mock instance.
func NewMockPubSub(ctrl *gomock.Controller) *MockPubSub { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPubSub) EXPECT() *MockPubSubMockRecorder {
	_ = "STUB: not implemented"

	// Close mocks base method.
	return nil
}

func (m *MockPubSub) Close() error { _ = "STUB: not implemented"; return nil }

// Close indicates an expected call of Close.
func (mr *MockPubSubMockRecorder) Close() *gomock.Call { _ = "STUB: not implemented"; return nil }

// Features mocks base method.
func (m *MockPubSub) Features() []pubsub.Feature { _ = "STUB: not implemented"; return nil }

// Features indicates an expected call of Features.
func (mr *MockPubSubMockRecorder) Features() *gomock.Call { _ = "STUB: not implemented"; return nil }

// Init mocks base method.
func (m *MockPubSub) Init(arg0 pubsub.Metadata) error { _ = "STUB: not implemented"; return nil }

// Init indicates an expected call of Init.
func (mr *MockPubSubMockRecorder) Init(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Publish mocks base method.
func (m *MockPubSub) Publish(arg0 *pubsub.PublishRequest) error {
	_ = "STUB: not implemented"
	return nil
}

// Publish indicates an expected call of Publish.
func (mr *MockPubSubMockRecorder) Publish(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Subscribe mocks base method.
func (m *MockPubSub) Subscribe(arg0 pubsub.SubscribeRequest, arg1 pubsub.Handler) error {
	_ = "STUB: not implemented"
	return nil
}

// Subscribe indicates an expected call of Subscribe.
func (mr *MockPubSubMockRecorder) Subscribe(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
