//
// Copyright 2021 Layotto Authors
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by MockGen. DO NOT EDIT.
// Source: ./consul.go

// Package utils is a generated GoMock package.
package mock

import (
	gomock "github.com/golang/mock/gomock"
	api "github.com/hashicorp/consul/api"
)

// MockConsulClient is a mock of ConsulClient interface.
type MockConsulClient struct {
	ctrl     *gomock.Controller
	recorder *MockConsulClientMockRecorder
}

// MockConsulClientMockRecorder is the mock recorder for MockConsulClient.
type MockConsulClientMockRecorder struct {
	mock *MockConsulClient
}

// NewMockConsulClient creates a new mock instance.
func NewMockConsulClient(ctrl *gomock.Controller) *MockConsulClient {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConsulClient) EXPECT() *MockConsulClientMockRecorder {
	_ = "STUB: not implemented"

	// Session mocks base method.
	return nil
}

func (m *MockConsulClient) Session() *api.Session { _ = "STUB: not implemented"; return nil }

// Session indicates an expected call of Session.
func (mr *MockConsulClientMockRecorder) Session() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockConsulKV is a mock of ConsulKV interface.
type MockConsulKV struct {
	ctrl     *gomock.Controller
	recorder *MockConsulKVMockRecorder
}

// MockConsulKVMockRecorder is the mock recorder for MockConsulKV.
type MockConsulKVMockRecorder struct {
	mock *MockConsulKV
}

// NewMockConsulKV creates a new mock instance.
func NewMockConsulKV(ctrl *gomock.Controller) *MockConsulKV { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConsulKV) EXPECT() *MockConsulKVMockRecorder {
	_ = "STUB: not implemented"

	// Acquire mocks base method.
	return nil
}

func (m *MockConsulKV) Acquire(p *api.KVPair, q *api.WriteOptions) (bool, *api.WriteMeta, error) {
	_ = "STUB: not implemented"
	return false, nil, nil
}

// Acquire indicates an expected call of Acquire.
func (mr *MockConsulKVMockRecorder) Acquire(p, q interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Release mocks base method.
func (m *MockConsulKV) Release(p *api.KVPair, q *api.WriteOptions) (bool, *api.WriteMeta, error) {
	_ = "STUB: not implemented"
	return false, nil, nil
}

// Release indicates an expected call of Release.
func (mr *MockConsulKVMockRecorder) Release(p, q interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockSessionFactory is a mock of SessionFactory interface.
type MockSessionFactory struct {
	ctrl     *gomock.Controller
	recorder *MockSessionFactoryMockRecorder
}

// MockSessionFactoryMockRecorder is the mock recorder for MockSessionFactory.
type MockSessionFactoryMockRecorder struct {
	mock *MockSessionFactory
}

// NewMockSessionFactory creates a new mock instance.
func NewMockSessionFactory(ctrl *gomock.Controller) *MockSessionFactory {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionFactory) EXPECT() *MockSessionFactoryMockRecorder {
	_ = "STUB: not implemented"

	// Create mocks base method.
	return nil
}

func (m *MockSessionFactory) Create(se *api.SessionEntry, q *api.WriteOptions) (string, *api.WriteMeta, error) {
	_ = "STUB: not implemented"
	return "", nil, nil
}

// Create indicates an expected call of Create.
func (mr *MockSessionFactoryMockRecorder) Create(se, q interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Destroy mocks base method.
func (m *MockSessionFactory) Destroy(id string, q *api.WriteOptions) (*api.WriteMeta, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Destroy indicates an expected call of Destroy.
func (mr *MockSessionFactoryMockRecorder) Destroy(id, q interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
