// Copyright 2021 Layotto Authors
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// Code generated by MockGen. DO NOT EDIT.
// Source: nacos_client.go

// Package mock_nacos is a generated GoMock package.
package mock

import (
	gomock "github.com/golang/mock/gomock"
	model "github.com/nacos-group/nacos-sdk-go/v2/model"
	vo "github.com/nacos-group/nacos-sdk-go/v2/vo"
)

// MockNacosConfigClient is a mock of NacosConfigClient interface.
type MockNacosConfigClient struct {
	ctrl     *gomock.Controller
	recorder *MockNacosConfigClientMockRecorder
}

// MockNacosConfigClientMockRecorder is the mock recorder for MockNacosConfigClient.
type MockNacosConfigClientMockRecorder struct {
	mock *MockNacosConfigClient
}

// NewMockNacosConfigClient creates a new mock instance.
func NewMockNacosConfigClient(ctrl *gomock.Controller) *MockNacosConfigClient {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNacosConfigClient) EXPECT() *MockNacosConfigClientMockRecorder {
	_ = "STUB: not implemented"

	// CancelListenConfig mocks base method.
	return nil
}

func (m *MockNacosConfigClient) CancelListenConfig(params vo.ConfigParam) error {
	_ = "STUB: not implemented"
	return nil
}

// CancelListenConfig indicates an expected call of CancelListenConfig.
func (mr *MockNacosConfigClientMockRecorder) CancelListenConfig(params interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// CloseClient mocks base method.
func (m *MockNacosConfigClient) CloseClient() { _ = "STUB: not implemented"; return }

// CloseClient indicates an expected call of CloseClient.
func (mr *MockNacosConfigClientMockRecorder) CloseClient() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// DeleteConfig mocks base method.
func (m *MockNacosConfigClient) DeleteConfig(param vo.ConfigParam) (bool, error) {
	_ = "STUB: not implemented"
	return false, nil
}

// DeleteConfig indicates an expected call of DeleteConfig.
func (mr *MockNacosConfigClientMockRecorder) DeleteConfig(param interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetConfig mocks base method.
func (m *MockNacosConfigClient) GetConfig(param vo.ConfigParam) (string, error) {
	_ = "STUB: not implemented"
	return "", nil
}

// GetConfig indicates an expected call of GetConfig.
func (mr *MockNacosConfigClientMockRecorder) GetConfig(param interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ListenConfig mocks base method.
func (m *MockNacosConfigClient) ListenConfig(params vo.ConfigParam) error {
	_ = "STUB: not implemented"
	return nil
}

// ListenConfig indicates an expected call of ListenConfig.
func (mr *MockNacosConfigClientMockRecorder) ListenConfig(params interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// PublishConfig mocks base method.
func (m *MockNacosConfigClient) PublishConfig(param vo.ConfigParam) (bool, error) {
	_ = "STUB: not implemented"
	return false, nil
}

// PublishConfig indicates an expected call of PublishConfig.
func (mr *MockNacosConfigClientMockRecorder) PublishConfig(param interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SearchConfig mocks base method.
func (m *MockNacosConfigClient) SearchConfig(param vo.SearchConfigParam) (*model.ConfigPage, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// SearchConfig indicates an expected call of SearchConfig.
func (mr *MockNacosConfigClientMockRecorder) SearchConfig(param interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
