/*
 * Copyright 2021 Layotto Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by MockGen. DO NOT EDIT.
// Source: qiniu_oss_client.go

// Package qiniu is a generated GoMock package.
package mock

import (
	context "context"
	io "io"

	gomock "github.com/golang/mock/gomock"
	storage "github.com/qiniu/go-sdk/v7/storage"
)

// MockFormUploader is a mock of FormUploader interface.
type MockFormUploader struct {
	ctrl     *gomock.Controller
	recorder *MockFormUploaderMockRecorder
}

// MockFormUploaderMockRecorder is the mock recorder for MockFormUploader.
type MockFormUploaderMockRecorder struct {
	mock *MockFormUploader
}

// NewMockFormUploader creates a new mock instance.
func NewMockFormUploader(ctrl *gomock.Controller) *MockFormUploader {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFormUploader) EXPECT() *MockFormUploaderMockRecorder {
	_ = "STUB: not implemented"

	// Put mocks base method.
	return nil
}

func (m *MockFormUploader) Put(ctx context.Context, ret interface{}, uptoken, key string, data io.Reader, size int64, extra *storage.PutExtra) error {
	_ = "STUB: not implemented"
	return nil
}

// Put indicates an expected call of Put.
func (mr *MockFormUploaderMockRecorder) Put(ctx, ret, uptoken, key, data, size, extra interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockBucketManager is a mock of BucketManager interface.
type MockBucketManager struct {
	ctrl     *gomock.Controller
	recorder *MockBucketManagerMockRecorder
}

// MockBucketManagerMockRecorder is the mock recorder for MockBucketManager.
type MockBucketManagerMockRecorder struct {
	mock *MockBucketManager
}

// NewMockBucketManager creates a new mock instance.
func NewMockBucketManager(ctrl *gomock.Controller) *MockBucketManager {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBucketManager) EXPECT() *MockBucketManagerMockRecorder {
	_ = "STUB: not implemented"

	// Delete mocks base method.
	return nil
}

func (m *MockBucketManager) Delete(bucket, key string) error { _ = "STUB: not implemented"; return nil }

// Delete indicates an expected call of Delete.
func (mr *MockBucketManagerMockRecorder) Delete(bucket, key interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ListFiles mocks base method.
func (m *MockBucketManager) ListFiles(bucket, prefix, delimiter, marker string, limit int) ([]storage.ListItem, []string, string, bool, error) {
	_ = "STUB: not implemented"
	return nil, nil, "", false, nil
}

// ListFiles indicates an expected call of ListFiles.
func (mr *MockBucketManagerMockRecorder) ListFiles(bucket, prefix, delimiter, marker, limit interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Stat mocks base method.
func (m *MockBucketManager) Stat(bucket, key string) (storage.FileInfo, error) {
	_ = "STUB: not implemented"
	return *new(storage.FileInfo), nil
}

// Stat indicates an expected call of Stat.
func (mr *MockBucketManagerMockRecorder) Stat(bucket, key interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
