//
// Copyright 2021 Layotto Authors
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// Code generated by MockGen. DO NOT EDIT.
// Source: zookeeper.go

// Package utils is a generated GoMock package.
package mock

import (
	time "time"

	"mosn.io/layotto/components/pkg/utils"

	zk "github.com/go-zookeeper/zk"
	gomock "github.com/golang/mock/gomock"
)

// MockConnectionFactory is a mock of ConnectionFactory interface.
type MockConnectionFactory struct {
	ctrl     *gomock.Controller
	recorder *MockConnectionFactoryMockRecorder
}

// MockConnectionFactoryMockRecorder is the mock recorder for MockConnectionFactory.
type MockConnectionFactoryMockRecorder struct {
	mock *MockConnectionFactory
}

// NewMockConnectionFactory creates a new mock instance.
func NewMockConnectionFactory(ctrl *gomock.Controller) *MockConnectionFactory {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConnectionFactory) EXPECT() *MockConnectionFactoryMockRecorder {
	_ = "STUB: not implemented"

	// NewConnection mocks base method.
	return nil
}

func (m *MockConnectionFactory) NewConnection(expire time.Duration, meta utils.ZookeeperMetadata) (utils.ZKConnection, error) {
	_ = "STUB: not implemented"
	return *new(utils.ZKConnection), nil
}

// NewConnection indicates an expected call of NewConnection.
func (mr *MockConnectionFactoryMockRecorder) NewConnection(expire, meta interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockZKConnection is a mock of ZKConnection interface.
type MockZKConnection struct {
	ctrl     *gomock.Controller
	recorder *MockZKConnectionMockRecorder
}

// MockZKConnectionMockRecorder is the mock recorder for MockZKConnection.
type MockZKConnectionMockRecorder struct {
	mock *MockZKConnection
}

// NewMockZKConnection creates a new mock instance.
func NewMockZKConnection(ctrl *gomock.Controller) *MockZKConnection {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockZKConnection) EXPECT() *MockZKConnectionMockRecorder {
	_ = "STUB: not implemented"

	// Close mocks base method.
	return nil
}

func (m *MockZKConnection) Close() { _ = "STUB: not implemented"; return }

// Close indicates an expected call of Close.
func (mr *MockZKConnectionMockRecorder) Close() *gomock.Call { _ = "STUB: not implemented"; return nil }

// Create mocks base method.
func (m *MockZKConnection) Create(path string, data []byte, flags int32, acl []zk.ACL) (string, error) {
	_ = "STUB: not implemented"
	return "", nil
}

// Create indicates an expected call of Create.
func (mr *MockZKConnectionMockRecorder) Create(path, data, flags, acl interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Delete mocks base method.
func (m *MockZKConnection) Delete(path string, version int32) error {
	_ = "STUB: not implemented"
	return nil
}

// Delete indicates an expected call of Delete.
func (mr *MockZKConnectionMockRecorder) Delete(path, version interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Get mocks base method.
func (m *MockZKConnection) Get(path string) ([]byte, *zk.Stat, error) {
	_ = "STUB: not implemented"
	return nil, nil, nil
}

// Get indicates an expected call of Get.
func (mr *MockZKConnectionMockRecorder) Get(path interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Set mocks base method.
func (m *MockZKConnection) Set(path string, data []byte, version int32) (*zk.Stat, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Set indicates an expected call of Set.
func (mr *MockZKConnectionMockRecorder) Set(path, data, version interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
