// Code generated by MockGen. DO NOT EDIT.
// Source: components/rpc/types.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"

	gomock "github.com/golang/mock/gomock"

	rpc "mosn.io/layotto/components/rpc"
)

// MockInvoker is a mock of Invoker interface.
type MockInvoker struct {
	ctrl     *gomock.Controller
	recorder *MockInvokerMockRecorder
}

// MockInvokerMockRecorder is the mock recorder for MockInvoker.
type MockInvokerMockRecorder struct {
	mock *MockInvoker
}

// NewMockInvoker creates a new mock instance.
func NewMockInvoker(ctrl *gomock.Controller) *MockInvoker { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInvoker) EXPECT() *MockInvokerMockRecorder {
	_ = "STUB: not implemented"

	// Init mocks base method.
	return nil
}

func (m *MockInvoker) Init(config rpc.RpcConfig) error { _ = "STUB: not implemented"; return nil }

// Init indicates an expected call of Init.
func (mr *MockInvokerMockRecorder) Init(config interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Invoke mocks base method.
func (m *MockInvoker) Invoke(ctx context.Context, req *rpc.RPCRequest) (*rpc.RPCResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Invoke indicates an expected call of Invoke.
func (mr *MockInvokerMockRecorder) Invoke(ctx, req interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockCallback is a mock of Callback interface.
type MockCallback struct {
	ctrl     *gomock.Controller
	recorder *MockCallbackMockRecorder
}

// MockCallbackMockRecorder is the mock recorder for MockCallback.
type MockCallbackMockRecorder struct {
	mock *MockCallback
}

// NewMockCallback creates a new mock instance.
func NewMockCallback(ctrl *gomock.Controller) *MockCallback { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCallback) EXPECT() *MockCallbackMockRecorder {
	_ = "STUB: not implemented"

	// AddAfterInvoke mocks base method.
	return nil
}

func (m *MockCallback) AddAfterInvoke(arg0 rpc.CallbackFunc) { _ = "STUB: not implemented"; return }

// AddAfterInvoke indicates an expected call of AddAfterInvoke.
func (mr *MockCallbackMockRecorder) AddAfterInvoke(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// AddBeforeInvoke mocks base method.
func (m *MockCallback) AddBeforeInvoke(arg0 rpc.CallbackFunc) { _ = "STUB: not implemented"; return }

// AddBeforeInvoke indicates an expected call of AddBeforeInvoke.
func (mr *MockCallbackMockRecorder) AddBeforeInvoke(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// AfterInvoke mocks base method.
func (m *MockCallback) AfterInvoke(arg0 *rpc.RPCResponse) (*rpc.RPCResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// AfterInvoke indicates an expected call of AfterInvoke.
func (mr *MockCallbackMockRecorder) AfterInvoke(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// BeforeInvoke mocks base method.
func (m *MockCallback) BeforeInvoke(arg0 *rpc.RPCRequest) (*rpc.RPCRequest, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// BeforeInvoke indicates an expected call of BeforeInvoke.
func (mr *MockCallbackMockRecorder) BeforeInvoke(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockChannel is a mock of Channel interface.
type MockChannel struct {
	ctrl     *gomock.Controller
	recorder *MockChannelMockRecorder
}

// MockChannelMockRecorder is the mock recorder for MockChannel.
type MockChannelMockRecorder struct {
	mock *MockChannel
}

// NewMockChannel creates a new mock instance.
func NewMockChannel(ctrl *gomock.Controller) *MockChannel { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChannel) EXPECT() *MockChannelMockRecorder {
	_ = "STUB: not implemented"

	// Do mocks base method.
	return nil
}

func (m *MockChannel) Do(arg0 *rpc.RPCRequest) (*rpc.RPCResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Do indicates an expected call of Do.
func (mr *MockChannelMockRecorder) Do(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
