// Code generated by MockGen. DO NOT EDIT.
// Source: oss.go

// Package mock_oss is a generated GoMock package.
package mock_oss

import (
	context "context"

	gomock "github.com/golang/mock/gomock"

	oss "mosn.io/layotto/components/oss"
)

// MockOss is a mock of Oss interface.
type MockOss struct {
	ctrl     *gomock.Controller
	recorder *MockOssMockRecorder
}

// MockOssMockRecorder is the mock recorder for MockOss.
type MockOssMockRecorder struct {
	mock *MockOss
}

// NewMockOss creates a new mock instance.
func NewMockOss(ctrl *gomock.Controller) *MockOss { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOss) EXPECT() *MockOssMockRecorder {
	_ = "STUB: not implemented"

	// AbortMultipartUpload mocks base method.
	return nil
}

func (m *MockOss) AbortMultipartUpload(arg0 context.Context, arg1 *oss.AbortMultipartUploadInput) (*oss.AbortMultipartUploadOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// AbortMultipartUpload indicates an expected call of AbortMultipartUpload.
func (mr *MockOssMockRecorder) AbortMultipartUpload(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// AppendObject mocks base method.
func (m *MockOss) AppendObject(arg0 context.Context, arg1 *oss.AppendObjectInput) (*oss.AppendObjectOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// AppendObject indicates an expected call of AppendObject.
func (mr *MockOssMockRecorder) AppendObject(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// CompleteMultipartUpload mocks base method.
func (m *MockOss) CompleteMultipartUpload(arg0 context.Context, arg1 *oss.CompleteMultipartUploadInput) (*oss.CompleteMultipartUploadOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CompleteMultipartUpload indicates an expected call of CompleteMultipartUpload.
func (mr *MockOssMockRecorder) CompleteMultipartUpload(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// CopyObject mocks base method.
func (m *MockOss) CopyObject(arg0 context.Context, arg1 *oss.CopyObjectInput) (*oss.CopyObjectOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CopyObject indicates an expected call of CopyObject.
func (mr *MockOssMockRecorder) CopyObject(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// CreateMultipartUpload mocks base method.
func (m *MockOss) CreateMultipartUpload(arg0 context.Context, arg1 *oss.CreateMultipartUploadInput) (*oss.CreateMultipartUploadOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateMultipartUpload indicates an expected call of CreateMultipartUpload.
func (mr *MockOssMockRecorder) CreateMultipartUpload(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// DeleteObject mocks base method.
func (m *MockOss) DeleteObject(arg0 context.Context, arg1 *oss.DeleteObjectInput) (*oss.DeleteObjectOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteObject indicates an expected call of DeleteObject.
func (mr *MockOssMockRecorder) DeleteObject(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// DeleteObjectTagging mocks base method.
func (m *MockOss) DeleteObjectTagging(arg0 context.Context, arg1 *oss.DeleteObjectTaggingInput) (*oss.DeleteObjectTaggingOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteObjectTagging indicates an expected call of DeleteObjectTagging.
func (mr *MockOssMockRecorder) DeleteObjectTagging(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// DeleteObjects mocks base method.
func (m *MockOss) DeleteObjects(arg0 context.Context, arg1 *oss.DeleteObjectsInput) (*oss.DeleteObjectsOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteObjects indicates an expected call of DeleteObjects.
func (mr *MockOssMockRecorder) DeleteObjects(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetObject mocks base method.
func (m *MockOss) GetObject(arg0 context.Context, arg1 *oss.GetObjectInput) (*oss.GetObjectOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetObject indicates an expected call of GetObject.
func (mr *MockOssMockRecorder) GetObject(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetObjectCannedAcl mocks base method.
func (m *MockOss) GetObjectCannedAcl(arg0 context.Context, arg1 *oss.GetObjectCannedAclInput) (*oss.GetObjectCannedAclOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetObjectCannedAcl indicates an expected call of GetObjectCannedAcl.
func (mr *MockOssMockRecorder) GetObjectCannedAcl(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetObjectTagging mocks base method.
func (m *MockOss) GetObjectTagging(arg0 context.Context, arg1 *oss.GetObjectTaggingInput) (*oss.GetObjectTaggingOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetObjectTagging indicates an expected call of GetObjectTagging.
func (mr *MockOssMockRecorder) GetObjectTagging(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// HeadObject mocks base method.
func (m *MockOss) HeadObject(arg0 context.Context, arg1 *oss.HeadObjectInput) (*oss.HeadObjectOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// HeadObject indicates an expected call of HeadObject.
func (mr *MockOssMockRecorder) HeadObject(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Init mocks base method.
func (m *MockOss) Init(arg0 context.Context, arg1 *oss.Config) error {
	_ = "STUB: not implemented"
	return nil
}

// Init indicates an expected call of Init.
func (mr *MockOssMockRecorder) Init(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// IsObjectExist mocks base method.
func (m *MockOss) IsObjectExist(arg0 context.Context, arg1 *oss.IsObjectExistInput) (*oss.IsObjectExistOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// IsObjectExist indicates an expected call of IsObjectExist.
func (mr *MockOssMockRecorder) IsObjectExist(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ListMultipartUploads mocks base method.
func (m *MockOss) ListMultipartUploads(arg0 context.Context, arg1 *oss.ListMultipartUploadsInput) (*oss.ListMultipartUploadsOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListMultipartUploads indicates an expected call of ListMultipartUploads.
func (mr *MockOssMockRecorder) ListMultipartUploads(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ListObjectVersions mocks base method.
func (m *MockOss) ListObjectVersions(arg0 context.Context, arg1 *oss.ListObjectVersionsInput) (*oss.ListObjectVersionsOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListObjectVersions indicates an expected call of ListObjectVersions.
func (mr *MockOssMockRecorder) ListObjectVersions(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ListObjects mocks base method.
func (m *MockOss) ListObjects(arg0 context.Context, arg1 *oss.ListObjectsInput) (*oss.ListObjectsOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListObjects indicates an expected call of ListObjects.
func (mr *MockOssMockRecorder) ListObjects(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ListParts mocks base method.
func (m *MockOss) ListParts(arg0 context.Context, arg1 *oss.ListPartsInput) (*oss.ListPartsOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListParts indicates an expected call of ListParts.
func (mr *MockOssMockRecorder) ListParts(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// PutObject mocks base method.
func (m *MockOss) PutObject(arg0 context.Context, arg1 *oss.PutObjectInput) (*oss.PutObjectOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PutObject indicates an expected call of PutObject.
func (mr *MockOssMockRecorder) PutObject(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// PutObjectCannedAcl mocks base method.
func (m *MockOss) PutObjectCannedAcl(arg0 context.Context, arg1 *oss.PutObjectCannedAclInput) (*oss.PutObjectCannedAclOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PutObjectCannedAcl indicates an expected call of PutObjectCannedAcl.
func (mr *MockOssMockRecorder) PutObjectCannedAcl(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// PutObjectTagging mocks base method.
func (m *MockOss) PutObjectTagging(arg0 context.Context, arg1 *oss.PutObjectTaggingInput) (*oss.PutObjectTaggingOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PutObjectTagging indicates an expected call of PutObjectTagging.
func (mr *MockOssMockRecorder) PutObjectTagging(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// RestoreObject mocks base method.
func (m *MockOss) RestoreObject(arg0 context.Context, arg1 *oss.RestoreObjectInput) (*oss.RestoreObjectOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// RestoreObject indicates an expected call of RestoreObject.
func (mr *MockOssMockRecorder) RestoreObject(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SignURL mocks base method.
func (m *MockOss) SignURL(arg0 context.Context, arg1 *oss.SignURLInput) (*oss.SignURLOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// SignURL indicates an expected call of SignURL.
func (mr *MockOssMockRecorder) SignURL(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// UpdateDownloadBandwidthRateLimit mocks base method.
func (m *MockOss) UpdateDownloadBandwidthRateLimit(arg0 context.Context, arg1 *oss.UpdateBandwidthRateLimitInput) error {
	_ = "STUB: not implemented"
	return nil
}

// UpdateDownloadBandwidthRateLimit indicates an expected call of UpdateDownloadBandwidthRateLimit.
func (mr *MockOssMockRecorder) UpdateDownloadBandwidthRateLimit(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// UpdateUploadBandwidthRateLimit mocks base method.
func (m *MockOss) UpdateUploadBandwidthRateLimit(arg0 context.Context, arg1 *oss.UpdateBandwidthRateLimitInput) error {
	_ = "STUB: not implemented"
	return nil
}

// UpdateUploadBandwidthRateLimit indicates an expected call of UpdateUploadBandwidthRateLimit.
func (mr *MockOssMockRecorder) UpdateUploadBandwidthRateLimit(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// UploadPart mocks base method.
func (m *MockOss) UploadPart(arg0 context.Context, arg1 *oss.UploadPartInput) (*oss.UploadPartOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UploadPart indicates an expected call of UploadPart.
func (mr *MockOssMockRecorder) UploadPart(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// UploadPartCopy mocks base method.
func (m *MockOss) UploadPartCopy(arg0 context.Context, arg1 *oss.UploadPartCopyInput) (*oss.UploadPartCopyOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UploadPartCopy indicates an expected call of UploadPartCopy.
func (mr *MockOssMockRecorder) UploadPartCopy(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
