// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/dapr/components-contrib/state (interfaces: Store,TransactionalStore)

// Package mock_state is a generated GoMock package.
package mock_state

import (
	state "github.com/dapr/components-contrib/state"
	gomock "github.com/golang/mock/gomock"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	_ = "STUB: not implemented"

	// BulkDelete mocks base method.
	return nil
}

func (m *MockStore) BulkDelete(arg0 []state.DeleteRequest) error {
	_ = "STUB: not implemented"
	return nil
}

// BulkDelete indicates an expected call of BulkDelete.
func (mr *MockStoreMockRecorder) BulkDelete(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// BulkGet mocks base method.
func (m *MockStore) BulkGet(arg0 []state.GetRequest) (bool, []state.BulkGetResponse, error) {
	_ = "STUB: not implemented"
	return false, nil, nil
}

// BulkGet indicates an expected call of BulkGet.
func (mr *MockStoreMockRecorder) BulkGet(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// BulkSet mocks base method.
func (m *MockStore) BulkSet(arg0 []state.SetRequest) error { _ = "STUB: not implemented"; return nil }

// BulkSet mocks base method.
func (m *MockStore) Ping() error { _ = "STUB: not implemented"; return nil }

// BulkSet indicates an expected call of BulkSet.
func (mr *MockStoreMockRecorder) BulkSet(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Delete mocks base method.
func (m *MockStore) Delete(arg0 *state.DeleteRequest) error { _ = "STUB: not implemented"; return nil }

// Delete indicates an expected call of Delete.
func (mr *MockStoreMockRecorder) Delete(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Features mocks base method.
func (m *MockStore) Features() []state.Feature { _ = "STUB: not implemented"; return nil }

// Features indicates an expected call of Features.
func (mr *MockStoreMockRecorder) Features() *gomock.Call { _ = "STUB: not implemented"; return nil }

// Get mocks base method.
func (m *MockStore) Get(arg0 *state.GetRequest) (*state.GetResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Get indicates an expected call of Get.
func (mr *MockStoreMockRecorder) Get(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Init mocks base method.
func (m *MockStore) Init(arg0 state.Metadata) error { _ = "STUB: not implemented"; return nil }

// Init indicates an expected call of Init.
func (mr *MockStoreMockRecorder) Init(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Set mocks base method.
func (m *MockStore) Set(arg0 *state.SetRequest) error { _ = "STUB: not implemented"; return nil }

// Set indicates an expected call of Set.
func (mr *MockStoreMockRecorder) Set(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockTransactionalStore is a mock of TransactionalStore interface.
type MockTransactionalStore struct {
	ctrl     *gomock.Controller
	recorder *MockTransactionalStoreMockRecorder
}

// MockTransactionalStoreMockRecorder is the mock recorder for MockTransactionalStore.
type MockTransactionalStoreMockRecorder struct {
	mock *MockTransactionalStore
}

// NewMockTransactionalStore creates a new mock instance.
func NewMockTransactionalStore(ctrl *gomock.Controller) *MockTransactionalStore {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransactionalStore) EXPECT() *MockTransactionalStoreMockRecorder {
	_ = "STUB: not implemented"

	// Init mocks base method.
	return nil
}

func (m *MockTransactionalStore) Init(arg0 state.Metadata) error {
	_ = "STUB: not implemented"
	return nil
}

// Init indicates an expected call of Init.
func (mr *MockTransactionalStoreMockRecorder) Init(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Multi mocks base method.
func (m *MockTransactionalStore) Multi(arg0 *state.TransactionalStateRequest) error {
	_ = "STUB: not implemented"
	return nil
}

// Multi indicates an expected call of Multi.
func (mr *MockTransactionalStoreMockRecorder) Multi(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
