// Code generated by MockGen. DO NOT EDIT.
// Source: configstore.go

// Package mock_configstores is a generated GoMock package.
package mock

import (
	context "context"

	"mosn.io/layotto/components/configstores"

	gomock "github.com/golang/mock/gomock"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
}

func (m *MockStore) GetDefaultGroup() string { _ = "STUB: not implemented"; return "" }

func (m *MockStore) GetDefaultLabel() string {
	_ = "STUB: not implemented"

	// MockStoreMockRecorder is the mock recorder for MockStore.
	return ""
}

type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	_ = "STUB: not implemented"

	// Delete mocks base method.
	return nil
}

func (m *MockStore) Delete(arg0 context.Context, arg1 *configstores.DeleteRequest) error {
	_ = "STUB: not implemented"
	return nil
}

// Delete indicates an expected call of Delete.
func (mr *MockStoreMockRecorder) Delete(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Get mocks base method.
func (m *MockStore) Get(arg0 context.Context, arg1 *configstores.GetRequest) ([]*configstores.ConfigurationItem, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Get indicates an expected call of Get.
func (mr *MockStoreMockRecorder) Get(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Init mocks base method.
func (m *MockStore) Init(config *configstores.StoreConfig) error {
	_ = "STUB: not implemented"
	return nil
}

// Init indicates an expected call of Init.
func (mr *MockStoreMockRecorder) Init(config interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Set mocks base method.
func (m *MockStore) Set(arg0 context.Context, arg1 *configstores.SetRequest) error {
	_ = "STUB: not implemented"
	return nil
}

// Set indicates an expected call of Set.
func (mr *MockStoreMockRecorder) Set(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// StopSubscribe mocks base method.
func (m *MockStore) StopSubscribe() { _ = "STUB: not implemented"; return }

// StopSubscribe indicates an expected call of StopSubscribe.
func (mr *MockStoreMockRecorder) StopSubscribe() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Subscribe mocks base method.
func (m *MockStore) Subscribe(arg0 *configstores.SubscribeReq, arg1 chan *configstores.SubscribeResp) error {
	_ = "STUB: not implemented"
	return nil
}

// Subscribe indicates an expected call of Subscribe.
func (mr *MockStoreMockRecorder) Subscribe(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
