// Code generated by MockGen. DO NOT EDIT.
// Source: file.go

// Package mock_file is a generated GoMock package.
package mock

import (
	context "context"
	io "io"

	gomock "github.com/golang/mock/gomock"

	file "mosn.io/layotto/components/file"
)

// MockFile is a mock of File interface.
type MockFile struct {
	ctrl     *gomock.Controller
	recorder *MockFileMockRecorder
}

// MockFileMockRecorder is the mock recorder for MockFile.
type MockFileMockRecorder struct {
	mock *MockFile
}

// NewMockFile creates a new mock instance.
func NewMockFile(ctrl *gomock.Controller) *MockFile { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFile) EXPECT() *MockFileMockRecorder {
	_ = "STUB: not implemented"

	// Del mocks base method.
	return nil
}

func (m *MockFile) Del(arg0 context.Context, arg1 *file.DelRequest) error {
	_ = "STUB: not implemented"
	return nil
}

// Del indicates an expected call of Del.
func (mr *MockFileMockRecorder) Del(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Get mocks base method.
func (m *MockFile) Get(arg0 context.Context, arg1 *file.GetFileStu) (io.ReadCloser, error) {
	_ = "STUB: not implemented"
	return *new(io.ReadCloser), nil
}

// Get indicates an expected call of Get.
func (mr *MockFileMockRecorder) Get(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Init mocks base method.
func (m *MockFile) Init(arg0 context.Context, arg1 *file.FileConfig) error {
	_ = "STUB: not implemented"
	return nil
}

// Init indicates an expected call of Init.
func (mr *MockFileMockRecorder) Init(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// List mocks base method.
func (m *MockFile) List(arg0 context.Context, arg1 *file.ListRequest) (*file.ListResp, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// List indicates an expected call of List.
func (mr *MockFileMockRecorder) List(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Put mocks base method.
func (m *MockFile) Put(arg0 context.Context, arg1 *file.PutFileStu) error {
	_ = "STUB: not implemented"
	return nil
}

// Put indicates an expected call of Put.
func (mr *MockFileMockRecorder) Put(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Stat mocks base method.
func (m *MockFile) Stat(arg0 context.Context, arg1 *file.FileMetaRequest) (*file.FileMetaResp, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Stat indicates an expected call of Stat.
func (mr *MockFileMockRecorder) Stat(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
