// Code generated by MockGen. DO NOT EDIT.
// Source: ../services/hello/hello.go

// Package mock is a generated GoMock package.
package mock

import (
	"context"

	"mosn.io/layotto/components/hello"

	gomock "github.com/golang/mock/gomock"
)

// MockHelloService is a mock of HelloService interface.
type MockHelloService struct {
	ctrl     *gomock.Controller
	recorder *MockHelloServiceMockRecorder
}

// MockHelloServiceMockRecorder is the mock recorder for MockHelloService.
type MockHelloServiceMockRecorder struct {
	mock *MockHelloService
}

// NewMockHelloService creates a new mock instance.
func NewMockHelloService(ctrl *gomock.Controller) *MockHelloService {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHelloService) EXPECT() *MockHelloServiceMockRecorder {
	_ = "STUB: not implemented"

	// Init mocks base method.
	return nil
}

func (m *MockHelloService) Init(arg0 *hello.HelloConfig) error {
	_ = "STUB: not implemented"
	return nil
}

// Init indicates an expected call of Init.
func (mr *MockHelloServiceMockRecorder) Init(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Hello mocks base method.
func (m *MockHelloService) Hello(ctx context.Context, arg0 *hello.HelloRequest) (*hello.HelloResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Hello indicates an expected call of Hello.
func (mr *MockHelloServiceMockRecorder) Hello(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
