// Code generated by MockGen. DO NOT EDIT.
// Source: runtime.pb.go

// Package mock_runtime is a generated GoMock package.
package runtime

import (
	context "context"

	gomock "github.com/golang/mock/gomock"
	grpc "google.golang.org/grpc"
	metadata "google.golang.org/grpc/metadata"
	emptypb "google.golang.org/protobuf/types/known/emptypb"

	runtime "mosn.io/layotto/spec/proto/runtime/v1"
)

// MockRuntimeClient is a mock of RuntimeClient interface.
type MockRuntimeClient struct {
	ctrl     *gomock.Controller
	recorder *MockRuntimeClientMockRecorder
}

// MockRuntimeClientMockRecorder is the mock recorder for MockRuntimeClient.
type MockRuntimeClientMockRecorder struct {
	mock *MockRuntimeClient
}

// NewMockRuntimeClient creates a new mock instance.
func NewMockRuntimeClient(ctrl *gomock.Controller) *MockRuntimeClient {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRuntimeClient) EXPECT() *MockRuntimeClientMockRecorder {
	_ = "STUB: not implemented"

	// DelFile mocks base method.
	return nil
}

func (m *MockRuntimeClient) DelFile(ctx context.Context, in *runtime.DelFileRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DelFile indicates an expected call of DelFile.
func (mr *MockRuntimeClientMockRecorder) DelFile(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// DeleteBulkState mocks base method.
func (m *MockRuntimeClient) DeleteBulkState(ctx context.Context, in *runtime.DeleteBulkStateRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteBulkState indicates an expected call of DeleteBulkState.
func (mr *MockRuntimeClientMockRecorder) DeleteBulkState(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// DeleteConfiguration mocks base method.
func (m *MockRuntimeClient) DeleteConfiguration(ctx context.Context, in *runtime.DeleteConfigurationRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteConfiguration indicates an expected call of DeleteConfiguration.
func (mr *MockRuntimeClientMockRecorder) DeleteConfiguration(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// DeleteState mocks base method.
func (m *MockRuntimeClient) DeleteState(ctx context.Context, in *runtime.DeleteStateRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteState indicates an expected call of DeleteState.
func (mr *MockRuntimeClientMockRecorder) DeleteState(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ExecuteStateTransaction mocks base method.
func (m *MockRuntimeClient) ExecuteStateTransaction(ctx context.Context, in *runtime.ExecuteStateTransactionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ExecuteStateTransaction indicates an expected call of ExecuteStateTransaction.
func (mr *MockRuntimeClientMockRecorder) ExecuteStateTransaction(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetBulkState mocks base method.
func (m *MockRuntimeClient) GetBulkState(ctx context.Context, in *runtime.GetBulkStateRequest, opts ...grpc.CallOption) (*runtime.GetBulkStateResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetBulkState indicates an expected call of GetBulkState.
func (mr *MockRuntimeClientMockRecorder) GetBulkState(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetConfiguration mocks base method.
func (m *MockRuntimeClient) GetConfiguration(ctx context.Context, in *runtime.GetConfigurationRequest, opts ...grpc.CallOption) (*runtime.GetConfigurationResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetConfiguration indicates an expected call of GetConfiguration.
func (mr *MockRuntimeClientMockRecorder) GetConfiguration(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetFile mocks base method.
func (m *MockRuntimeClient) GetFile(ctx context.Context, in *runtime.GetFileRequest, opts ...grpc.CallOption) (runtime.Runtime_GetFileClient, error) {
	_ = "STUB: not implemented"
	return *new(runtime.Runtime_GetFileClient), nil
}

// GetFile indicates an expected call of GetFile.
func (mr *MockRuntimeClientMockRecorder) GetFile(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetFileMeta mocks base method.
func (m *MockRuntimeClient) GetFileMeta(ctx context.Context, in *runtime.GetFileMetaRequest, opts ...grpc.CallOption) (*runtime.GetFileMetaResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetFileMeta indicates an expected call of GetFileMeta.
func (mr *MockRuntimeClientMockRecorder) GetFileMeta(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetNextId mocks base method.
func (m *MockRuntimeClient) GetNextId(ctx context.Context, in *runtime.GetNextIdRequest, opts ...grpc.CallOption) (*runtime.GetNextIdResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetNextId indicates an expected call of GetNextId.
func (mr *MockRuntimeClientMockRecorder) GetNextId(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetState mocks base method.
func (m *MockRuntimeClient) GetState(ctx context.Context, in *runtime.GetStateRequest, opts ...grpc.CallOption) (*runtime.GetStateResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetState indicates an expected call of GetState.
func (mr *MockRuntimeClientMockRecorder) GetState(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// InvokeBinding mocks base method.
func (m *MockRuntimeClient) InvokeBinding(ctx context.Context, in *runtime.InvokeBindingRequest, opts ...grpc.CallOption) (*runtime.InvokeBindingResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// InvokeBinding indicates an expected call of InvokeBinding.
func (mr *MockRuntimeClientMockRecorder) InvokeBinding(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// InvokeService mocks base method.
func (m *MockRuntimeClient) InvokeService(ctx context.Context, in *runtime.InvokeServiceRequest, opts ...grpc.CallOption) (*runtime.InvokeResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// InvokeService indicates an expected call of InvokeService.
func (mr *MockRuntimeClientMockRecorder) InvokeService(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ListFile mocks base method.
func (m *MockRuntimeClient) ListFile(ctx context.Context, in *runtime.ListFileRequest, opts ...grpc.CallOption) (*runtime.ListFileResp, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListFile indicates an expected call of ListFile.
func (mr *MockRuntimeClientMockRecorder) ListFile(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// PublishEvent mocks base method.
func (m *MockRuntimeClient) PublishEvent(ctx context.Context, in *runtime.PublishEventRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PublishEvent indicates an expected call of PublishEvent.
func (mr *MockRuntimeClientMockRecorder) PublishEvent(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// PutFile mocks base method.
func (m *MockRuntimeClient) PutFile(ctx context.Context, opts ...grpc.CallOption) (runtime.Runtime_PutFileClient, error) {
	_ = "STUB: not implemented"
	return *new(runtime.Runtime_PutFileClient), nil
}

// PutFile indicates an expected call of PutFile.
func (mr *MockRuntimeClientMockRecorder) PutFile(ctx interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SaveConfiguration mocks base method.
func (m *MockRuntimeClient) SaveConfiguration(ctx context.Context, in *runtime.SaveConfigurationRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// SaveConfiguration indicates an expected call of SaveConfiguration.
func (mr *MockRuntimeClientMockRecorder) SaveConfiguration(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SaveState mocks base method.
func (m *MockRuntimeClient) SaveState(ctx context.Context, in *runtime.SaveStateRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// SaveState indicates an expected call of SaveState.
func (mr *MockRuntimeClientMockRecorder) SaveState(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SayHello mocks base method.
func (m *MockRuntimeClient) SayHello(ctx context.Context, in *runtime.SayHelloRequest, opts ...grpc.CallOption) (*runtime.SayHelloResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// SayHello indicates an expected call of SayHello.
func (mr *MockRuntimeClientMockRecorder) SayHello(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SubscribeConfiguration mocks base method.
func (m *MockRuntimeClient) SubscribeConfiguration(ctx context.Context, opts ...grpc.CallOption) (runtime.Runtime_SubscribeConfigurationClient, error) {
	_ = "STUB: not implemented"
	return *new(runtime.Runtime_SubscribeConfigurationClient), nil
}

// SubscribeConfiguration indicates an expected call of SubscribeConfiguration.
func (mr *MockRuntimeClientMockRecorder) SubscribeConfiguration(ctx interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// TryLock mocks base method.
func (m *MockRuntimeClient) TryLock(ctx context.Context, in *runtime.TryLockRequest, opts ...grpc.CallOption) (*runtime.TryLockResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// TryLock indicates an expected call of TryLock.
func (mr *MockRuntimeClientMockRecorder) TryLock(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Unlock mocks base method.
func (m *MockRuntimeClient) Unlock(ctx context.Context, in *runtime.UnlockRequest, opts ...grpc.CallOption) (*runtime.UnlockResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Unlock indicates an expected call of Unlock.
func (mr *MockRuntimeClientMockRecorder) Unlock(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockRuntime_SubscribeConfigurationClient is a mock of Runtime_SubscribeConfigurationClient interface.
type MockRuntime_SubscribeConfigurationClient struct {
	ctrl     *gomock.Controller
	recorder *MockRuntime_SubscribeConfigurationClientMockRecorder
}

// MockRuntime_SubscribeConfigurationClientMockRecorder is the mock recorder for MockRuntime_SubscribeConfigurationClient.
type MockRuntime_SubscribeConfigurationClientMockRecorder struct {
	mock *MockRuntime_SubscribeConfigurationClient
}

// NewMockRuntime_SubscribeConfigurationClient creates a new mock instance.
func NewMockRuntime_SubscribeConfigurationClient(ctrl *gomock.Controller) *MockRuntime_SubscribeConfigurationClient {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRuntime_SubscribeConfigurationClient) EXPECT() *MockRuntime_SubscribeConfigurationClientMockRecorder {
	_ = "STUB: not implemented"

	// CloseSend mocks base method.
	return nil
}

func (m *MockRuntime_SubscribeConfigurationClient) CloseSend() error {
	_ = "STUB: not implemented"
	return nil
}

// CloseSend indicates an expected call of CloseSend.
func (mr *MockRuntime_SubscribeConfigurationClientMockRecorder) CloseSend() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Context mocks base method.
func (m *MockRuntime_SubscribeConfigurationClient) Context() context.Context {
	_ = "STUB: not implemented"
	return *new(context.Context)
}

// Context indicates an expected call of Context.
func (mr *MockRuntime_SubscribeConfigurationClientMockRecorder) Context() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Header mocks base method.
func (m *MockRuntime_SubscribeConfigurationClient) Header() (metadata.MD, error) {
	_ = "STUB: not implemented"
	return *new(metadata.MD), nil
}

// Header indicates an expected call of Header.
func (mr *MockRuntime_SubscribeConfigurationClientMockRecorder) Header() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Recv mocks base method.
func (m *MockRuntime_SubscribeConfigurationClient) Recv() (*runtime.SubscribeConfigurationResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Recv indicates an expected call of Recv.
func (mr *MockRuntime_SubscribeConfigurationClientMockRecorder) Recv() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// RecvMsg mocks base method.
func (m_2 *MockRuntime_SubscribeConfigurationClient) RecvMsg(m interface{}) error {
	_ = "STUB: not implemented"
	return nil
}

// RecvMsg indicates an expected call of RecvMsg.
func (mr *MockRuntime_SubscribeConfigurationClientMockRecorder) RecvMsg(m interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Send mocks base method.
func (m *MockRuntime_SubscribeConfigurationClient) Send(arg0 *runtime.SubscribeConfigurationRequest) error {
	_ = "STUB: not implemented"
	return nil
}

// Send indicates an expected call of Send.
func (mr *MockRuntime_SubscribeConfigurationClientMockRecorder) Send(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SendMsg mocks base method.
func (m_2 *MockRuntime_SubscribeConfigurationClient) SendMsg(m interface{}) error {
	_ = "STUB: not implemented"
	return nil
}

// SendMsg indicates an expected call of SendMsg.
func (mr *MockRuntime_SubscribeConfigurationClientMockRecorder) SendMsg(m interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Trailer mocks base method.
func (m *MockRuntime_SubscribeConfigurationClient) Trailer() metadata.MD {
	_ = "STUB: not implemented"
	return *new(metadata.MD)
}

// Trailer indicates an expected call of Trailer.
func (mr *MockRuntime_SubscribeConfigurationClientMockRecorder) Trailer() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockRuntime_GetFileClient is a mock of Runtime_GetFileClient interface.
type MockRuntime_GetFileClient struct {
	ctrl     *gomock.Controller
	recorder *MockRuntime_GetFileClientMockRecorder
}

// MockRuntime_GetFileClientMockRecorder is the mock recorder for MockRuntime_GetFileClient.
type MockRuntime_GetFileClientMockRecorder struct {
	mock *MockRuntime_GetFileClient
}

// NewMockRuntime_GetFileClient creates a new mock instance.
func NewMockRuntime_GetFileClient(ctrl *gomock.Controller) *MockRuntime_GetFileClient {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRuntime_GetFileClient) EXPECT() *MockRuntime_GetFileClientMockRecorder {
	_ = "STUB: not implemented"

	// CloseSend mocks base method.
	return nil
}

func (m *MockRuntime_GetFileClient) CloseSend() error { _ = "STUB: not implemented"; return nil }

// CloseSend indicates an expected call of CloseSend.
func (mr *MockRuntime_GetFileClientMockRecorder) CloseSend() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Context mocks base method.
func (m *MockRuntime_GetFileClient) Context() context.Context {
	_ = "STUB: not implemented"
	return *new(context.Context)
}

// Context indicates an expected call of Context.
func (mr *MockRuntime_GetFileClientMockRecorder) Context() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Header mocks base method.
func (m *MockRuntime_GetFileClient) Header() (metadata.MD, error) {
	_ = "STUB: not implemented"
	return *new(metadata.MD), nil
}

// Header indicates an expected call of Header.
func (mr *MockRuntime_GetFileClientMockRecorder) Header() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Recv mocks base method.
func (m *MockRuntime_GetFileClient) Recv() (*runtime.GetFileResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Recv indicates an expected call of Recv.
func (mr *MockRuntime_GetFileClientMockRecorder) Recv() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// RecvMsg mocks base method.
func (m_2 *MockRuntime_GetFileClient) RecvMsg(m interface{}) error {
	_ = "STUB: not implemented"
	return nil
}

// RecvMsg indicates an expected call of RecvMsg.
func (mr *MockRuntime_GetFileClientMockRecorder) RecvMsg(m interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SendMsg mocks base method.
func (m_2 *MockRuntime_GetFileClient) SendMsg(m interface{}) error {
	_ = "STUB: not implemented"
	return nil
}

// SendMsg indicates an expected call of SendMsg.
func (mr *MockRuntime_GetFileClientMockRecorder) SendMsg(m interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Trailer mocks base method.
func (m *MockRuntime_GetFileClient) Trailer() metadata.MD {
	_ = "STUB: not implemented"
	return *new(metadata.MD)
}

// Trailer indicates an expected call of Trailer.
func (mr *MockRuntime_GetFileClientMockRecorder) Trailer() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockRuntime_PutFileClient is a mock of Runtime_PutFileClient interface.
type MockRuntime_PutFileClient struct {
	ctrl     *gomock.Controller
	recorder *MockRuntime_PutFileClientMockRecorder
}

// MockRuntime_PutFileClientMockRecorder is the mock recorder for MockRuntime_PutFileClient.
type MockRuntime_PutFileClientMockRecorder struct {
	mock *MockRuntime_PutFileClient
}

// NewMockRuntime_PutFileClient creates a new mock instance.
func NewMockRuntime_PutFileClient(ctrl *gomock.Controller) *MockRuntime_PutFileClient {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRuntime_PutFileClient) EXPECT() *MockRuntime_PutFileClientMockRecorder {
	_ = "STUB: not implemented"

	// CloseAndRecv mocks base method.
	return nil
}

func (m *MockRuntime_PutFileClient) CloseAndRecv() (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CloseAndRecv indicates an expected call of CloseAndRecv.
func (mr *MockRuntime_PutFileClientMockRecorder) CloseAndRecv() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// CloseSend mocks base method.
func (m *MockRuntime_PutFileClient) CloseSend() error { _ = "STUB: not implemented"; return nil }

// CloseSend indicates an expected call of CloseSend.
func (mr *MockRuntime_PutFileClientMockRecorder) CloseSend() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Context mocks base method.
func (m *MockRuntime_PutFileClient) Context() context.Context {
	_ = "STUB: not implemented"
	return *new(context.Context)
}

// Context indicates an expected call of Context.
func (mr *MockRuntime_PutFileClientMockRecorder) Context() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Header mocks base method.
func (m *MockRuntime_PutFileClient) Header() (metadata.MD, error) {
	_ = "STUB: not implemented"
	return *new(metadata.MD), nil
}

// Header indicates an expected call of Header.
func (mr *MockRuntime_PutFileClientMockRecorder) Header() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// RecvMsg mocks base method.
func (m_2 *MockRuntime_PutFileClient) RecvMsg(m interface{}) error {
	_ = "STUB: not implemented"
	return nil
}

// RecvMsg indicates an expected call of RecvMsg.
func (mr *MockRuntime_PutFileClientMockRecorder) RecvMsg(m interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Send mocks base method.
func (m *MockRuntime_PutFileClient) Send(arg0 *runtime.PutFileRequest) error {
	_ = "STUB: not implemented"
	return nil
}

// Send indicates an expected call of Send.
func (mr *MockRuntime_PutFileClientMockRecorder) Send(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SendMsg mocks base method.
func (m_2 *MockRuntime_PutFileClient) SendMsg(m interface{}) error {
	_ = "STUB: not implemented"
	return nil
}

// SendMsg indicates an expected call of SendMsg.
func (mr *MockRuntime_PutFileClientMockRecorder) SendMsg(m interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Trailer mocks base method.
func (m *MockRuntime_PutFileClient) Trailer() metadata.MD {
	_ = "STUB: not implemented"
	return *new(metadata.MD)
}

// Trailer indicates an expected call of Trailer.
func (mr *MockRuntime_PutFileClientMockRecorder) Trailer() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockRuntimeServer is a mock of RuntimeServer interface.
type MockRuntimeServer struct {
	ctrl     *gomock.Controller
	recorder *MockRuntimeServerMockRecorder
}

// MockRuntimeServerMockRecorder is the mock recorder for MockRuntimeServer.
type MockRuntimeServerMockRecorder struct {
	mock *MockRuntimeServer
}

// NewMockRuntimeServer creates a new mock instance.
func NewMockRuntimeServer(ctrl *gomock.Controller) *MockRuntimeServer {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRuntimeServer) EXPECT() *MockRuntimeServerMockRecorder {
	_ = "STUB: not implemented"

	// DelFile mocks base method.
	return nil
}

func (m *MockRuntimeServer) DelFile(arg0 context.Context, arg1 *runtime.DelFileRequest) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DelFile indicates an expected call of DelFile.
func (mr *MockRuntimeServerMockRecorder) DelFile(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// DeleteBulkState mocks base method.
func (m *MockRuntimeServer) DeleteBulkState(arg0 context.Context, arg1 *runtime.DeleteBulkStateRequest) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteBulkState indicates an expected call of DeleteBulkState.
func (mr *MockRuntimeServerMockRecorder) DeleteBulkState(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// DeleteConfiguration mocks base method.
func (m *MockRuntimeServer) DeleteConfiguration(arg0 context.Context, arg1 *runtime.DeleteConfigurationRequest) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteConfiguration indicates an expected call of DeleteConfiguration.
func (mr *MockRuntimeServerMockRecorder) DeleteConfiguration(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// DeleteState mocks base method.
func (m *MockRuntimeServer) DeleteState(arg0 context.Context, arg1 *runtime.DeleteStateRequest) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteState indicates an expected call of DeleteState.
func (mr *MockRuntimeServerMockRecorder) DeleteState(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ExecuteStateTransaction mocks base method.
func (m *MockRuntimeServer) ExecuteStateTransaction(arg0 context.Context, arg1 *runtime.ExecuteStateTransactionRequest) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ExecuteStateTransaction indicates an expected call of ExecuteStateTransaction.
func (mr *MockRuntimeServerMockRecorder) ExecuteStateTransaction(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetBulkState mocks base method.
func (m *MockRuntimeServer) GetBulkState(arg0 context.Context, arg1 *runtime.GetBulkStateRequest) (*runtime.GetBulkStateResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetBulkState indicates an expected call of GetBulkState.
func (mr *MockRuntimeServerMockRecorder) GetBulkState(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetConfiguration mocks base method.
func (m *MockRuntimeServer) GetConfiguration(arg0 context.Context, arg1 *runtime.GetConfigurationRequest) (*runtime.GetConfigurationResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetConfiguration indicates an expected call of GetConfiguration.
func (mr *MockRuntimeServerMockRecorder) GetConfiguration(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetFile mocks base method.
func (m *MockRuntimeServer) GetFile(arg0 *runtime.GetFileRequest, arg1 runtime.Runtime_GetFileServer) error {
	_ = "STUB: not implemented"
	return nil
}

// GetFile indicates an expected call of GetFile.
func (mr *MockRuntimeServerMockRecorder) GetFile(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetFileMeta mocks base method.
func (m *MockRuntimeServer) GetFileMeta(arg0 context.Context, arg1 *runtime.GetFileMetaRequest) (*runtime.GetFileMetaResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetFileMeta indicates an expected call of GetFileMeta.
func (mr *MockRuntimeServerMockRecorder) GetFileMeta(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetNextId mocks base method.
func (m *MockRuntimeServer) GetNextId(arg0 context.Context, arg1 *runtime.GetNextIdRequest) (*runtime.GetNextIdResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetNextId indicates an expected call of GetNextId.
func (mr *MockRuntimeServerMockRecorder) GetNextId(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetState mocks base method.
func (m *MockRuntimeServer) GetState(arg0 context.Context, arg1 *runtime.GetStateRequest) (*runtime.GetStateResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetState indicates an expected call of GetState.
func (mr *MockRuntimeServerMockRecorder) GetState(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// InvokeBinding mocks base method.
func (m *MockRuntimeServer) InvokeBinding(arg0 context.Context, arg1 *runtime.InvokeBindingRequest) (*runtime.InvokeBindingResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// InvokeBinding indicates an expected call of InvokeBinding.
func (mr *MockRuntimeServerMockRecorder) InvokeBinding(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// InvokeService mocks base method.
func (m *MockRuntimeServer) InvokeService(arg0 context.Context, arg1 *runtime.InvokeServiceRequest) (*runtime.InvokeResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// InvokeService indicates an expected call of InvokeService.
func (mr *MockRuntimeServerMockRecorder) InvokeService(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ListFile mocks base method.
func (m *MockRuntimeServer) ListFile(arg0 context.Context, arg1 *runtime.ListFileRequest) (*runtime.ListFileResp, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListFile indicates an expected call of ListFile.
func (mr *MockRuntimeServerMockRecorder) ListFile(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// PublishEvent mocks base method.
func (m *MockRuntimeServer) PublishEvent(arg0 context.Context, arg1 *runtime.PublishEventRequest) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PublishEvent indicates an expected call of PublishEvent.
func (mr *MockRuntimeServerMockRecorder) PublishEvent(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// PutFile mocks base method.
func (m *MockRuntimeServer) PutFile(arg0 runtime.Runtime_PutFileServer) error {
	_ = "STUB: not implemented"
	return nil
}

// PutFile indicates an expected call of PutFile.
func (mr *MockRuntimeServerMockRecorder) PutFile(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SaveConfiguration mocks base method.
func (m *MockRuntimeServer) SaveConfiguration(arg0 context.Context, arg1 *runtime.SaveConfigurationRequest) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// SaveConfiguration indicates an expected call of SaveConfiguration.
func (mr *MockRuntimeServerMockRecorder) SaveConfiguration(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SaveState mocks base method.
func (m *MockRuntimeServer) SaveState(arg0 context.Context, arg1 *runtime.SaveStateRequest) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// SaveState indicates an expected call of SaveState.
func (mr *MockRuntimeServerMockRecorder) SaveState(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SayHello mocks base method.
func (m *MockRuntimeServer) SayHello(arg0 context.Context, arg1 *runtime.SayHelloRequest) (*runtime.SayHelloResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// SayHello indicates an expected call of SayHello.
func (mr *MockRuntimeServerMockRecorder) SayHello(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SubscribeConfiguration mocks base method.
func (m *MockRuntimeServer) SubscribeConfiguration(arg0 runtime.Runtime_SubscribeConfigurationServer) error {
	_ = "STUB: not implemented"
	return nil
}

// SubscribeConfiguration indicates an expected call of SubscribeConfiguration.
func (mr *MockRuntimeServerMockRecorder) SubscribeConfiguration(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// TryLock mocks base method.
func (m *MockRuntimeServer) TryLock(arg0 context.Context, arg1 *runtime.TryLockRequest) (*runtime.TryLockResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// TryLock indicates an expected call of TryLock.
func (mr *MockRuntimeServerMockRecorder) TryLock(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Unlock mocks base method.
func (m *MockRuntimeServer) Unlock(arg0 context.Context, arg1 *runtime.UnlockRequest) (*runtime.UnlockResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Unlock indicates an expected call of Unlock.
func (mr *MockRuntimeServerMockRecorder) Unlock(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockRuntime_SubscribeConfigurationServer is a mock of Runtime_SubscribeConfigurationServer interface.
type MockRuntime_SubscribeConfigurationServer struct {
	ctrl     *gomock.Controller
	recorder *MockRuntime_SubscribeConfigurationServerMockRecorder
}

// MockRuntime_SubscribeConfigurationServerMockRecorder is the mock recorder for MockRuntime_SubscribeConfigurationServer.
type MockRuntime_SubscribeConfigurationServerMockRecorder struct {
	mock *MockRuntime_SubscribeConfigurationServer
}

// NewMockRuntime_SubscribeConfigurationServer creates a new mock instance.
func NewMockRuntime_SubscribeConfigurationServer(ctrl *gomock.Controller) *MockRuntime_SubscribeConfigurationServer {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRuntime_SubscribeConfigurationServer) EXPECT() *MockRuntime_SubscribeConfigurationServerMockRecorder {
	_ = "STUB: not implemented"

	// Context mocks base method.
	return nil
}

func (m *MockRuntime_SubscribeConfigurationServer) Context() context.Context {
	_ = "STUB: not implemented"
	return *new(context.Context)
}

// Context indicates an expected call of Context.
func (mr *MockRuntime_SubscribeConfigurationServerMockRecorder) Context() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Recv mocks base method.
func (m *MockRuntime_SubscribeConfigurationServer) Recv() (*runtime.SubscribeConfigurationRequest, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Recv indicates an expected call of Recv.
func (mr *MockRuntime_SubscribeConfigurationServerMockRecorder) Recv() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// RecvMsg mocks base method.
func (m_2 *MockRuntime_SubscribeConfigurationServer) RecvMsg(m interface{}) error {
	_ = "STUB: not implemented"
	return nil
}

// RecvMsg indicates an expected call of RecvMsg.
func (mr *MockRuntime_SubscribeConfigurationServerMockRecorder) RecvMsg(m interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Send mocks base method.
func (m *MockRuntime_SubscribeConfigurationServer) Send(arg0 *runtime.SubscribeConfigurationResponse) error {
	_ = "STUB: not implemented"
	return nil
}

// Send indicates an expected call of Send.
func (mr *MockRuntime_SubscribeConfigurationServerMockRecorder) Send(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SendHeader mocks base method.
func (m *MockRuntime_SubscribeConfigurationServer) SendHeader(arg0 metadata.MD) error {
	_ = "STUB: not implemented"
	return nil
}

// SendHeader indicates an expected call of SendHeader.
func (mr *MockRuntime_SubscribeConfigurationServerMockRecorder) SendHeader(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SendMsg mocks base method.
func (m_2 *MockRuntime_SubscribeConfigurationServer) SendMsg(m interface{}) error {
	_ = "STUB: not implemented"
	return nil
}

// SendMsg indicates an expected call of SendMsg.
func (mr *MockRuntime_SubscribeConfigurationServerMockRecorder) SendMsg(m interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetHeader mocks base method.
func (m *MockRuntime_SubscribeConfigurationServer) SetHeader(arg0 metadata.MD) error {
	_ = "STUB: not implemented"
	return nil
}

// SetHeader indicates an expected call of SetHeader.
func (mr *MockRuntime_SubscribeConfigurationServerMockRecorder) SetHeader(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetTrailer mocks base method.
func (m *MockRuntime_SubscribeConfigurationServer) SetTrailer(arg0 metadata.MD) {
	_ = "STUB: not implemented"
	return
}

// SetTrailer indicates an expected call of SetTrailer.
func (mr *MockRuntime_SubscribeConfigurationServerMockRecorder) SetTrailer(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockRuntime_GetFileServer is a mock of Runtime_GetFileServer interface.
type MockRuntime_GetFileServer struct {
	ctrl     *gomock.Controller
	recorder *MockRuntime_GetFileServerMockRecorder
}

// MockRuntime_GetFileServerMockRecorder is the mock recorder for MockRuntime_GetFileServer.
type MockRuntime_GetFileServerMockRecorder struct {
	mock *MockRuntime_GetFileServer
}

// NewMockRuntime_GetFileServer creates a new mock instance.
func NewMockRuntime_GetFileServer(ctrl *gomock.Controller) *MockRuntime_GetFileServer {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRuntime_GetFileServer) EXPECT() *MockRuntime_GetFileServerMockRecorder {
	_ = "STUB: not implemented"

	// Context mocks base method.
	return nil
}

func (m *MockRuntime_GetFileServer) Context() context.Context {
	_ = "STUB: not implemented"
	return *new(context.Context)
}

// Context indicates an expected call of Context.
func (mr *MockRuntime_GetFileServerMockRecorder) Context() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// RecvMsg mocks base method.
func (m_2 *MockRuntime_GetFileServer) RecvMsg(m interface{}) error {
	_ = "STUB: not implemented"
	return nil
}

// RecvMsg indicates an expected call of RecvMsg.
func (mr *MockRuntime_GetFileServerMockRecorder) RecvMsg(m interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Send mocks base method.
func (m *MockRuntime_GetFileServer) Send(arg0 *runtime.GetFileResponse) error {
	_ = "STUB: not implemented"
	return nil
}

// Send indicates an expected call of Send.
func (mr *MockRuntime_GetFileServerMockRecorder) Send(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SendHeader mocks base method.
func (m *MockRuntime_GetFileServer) SendHeader(arg0 metadata.MD) error {
	_ = "STUB: not implemented"
	return nil
}

// SendHeader indicates an expected call of SendHeader.
func (mr *MockRuntime_GetFileServerMockRecorder) SendHeader(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SendMsg mocks base method.
func (m_2 *MockRuntime_GetFileServer) SendMsg(m interface{}) error {
	_ = "STUB: not implemented"
	return nil
}

// SendMsg indicates an expected call of SendMsg.
func (mr *MockRuntime_GetFileServerMockRecorder) SendMsg(m interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetHeader mocks base method.
func (m *MockRuntime_GetFileServer) SetHeader(arg0 metadata.MD) error {
	_ = "STUB: not implemented"
	return nil
}

// SetHeader indicates an expected call of SetHeader.
func (mr *MockRuntime_GetFileServerMockRecorder) SetHeader(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetTrailer mocks base method.
func (m *MockRuntime_GetFileServer) SetTrailer(arg0 metadata.MD) { _ = "STUB: not implemented"; return }

// SetTrailer indicates an expected call of SetTrailer.
func (mr *MockRuntime_GetFileServerMockRecorder) SetTrailer(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockRuntime_PutFileServer is a mock of Runtime_PutFileServer interface.
type MockRuntime_PutFileServer struct {
	ctrl     *gomock.Controller
	recorder *MockRuntime_PutFileServerMockRecorder
}

// MockRuntime_PutFileServerMockRecorder is the mock recorder for MockRuntime_PutFileServer.
type MockRuntime_PutFileServerMockRecorder struct {
	mock *MockRuntime_PutFileServer
}

// NewMockRuntime_PutFileServer creates a new mock instance.
func NewMockRuntime_PutFileServer(ctrl *gomock.Controller) *MockRuntime_PutFileServer {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRuntime_PutFileServer) EXPECT() *MockRuntime_PutFileServerMockRecorder {
	_ = "STUB: not implemented"

	// Context mocks base method.
	return nil
}

func (m *MockRuntime_PutFileServer) Context() context.Context {
	_ = "STUB: not implemented"
	return *new(context.Context)
}

// Context indicates an expected call of Context.
func (mr *MockRuntime_PutFileServerMockRecorder) Context() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Recv mocks base method.
func (m *MockRuntime_PutFileServer) Recv() (*runtime.PutFileRequest, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Recv indicates an expected call of Recv.
func (mr *MockRuntime_PutFileServerMockRecorder) Recv() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// RecvMsg mocks base method.
func (m_2 *MockRuntime_PutFileServer) RecvMsg(m interface{}) error {
	_ = "STUB: not implemented"
	return nil
}

// RecvMsg indicates an expected call of RecvMsg.
func (mr *MockRuntime_PutFileServerMockRecorder) RecvMsg(m interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SendAndClose mocks base method.
func (m *MockRuntime_PutFileServer) SendAndClose(arg0 *emptypb.Empty) error {
	_ = "STUB: not implemented"
	return nil
}

// SendAndClose indicates an expected call of SendAndClose.
func (mr *MockRuntime_PutFileServerMockRecorder) SendAndClose(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SendHeader mocks base method.
func (m *MockRuntime_PutFileServer) SendHeader(arg0 metadata.MD) error {
	_ = "STUB: not implemented"
	return nil
}

// SendHeader indicates an expected call of SendHeader.
func (mr *MockRuntime_PutFileServerMockRecorder) SendHeader(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SendMsg mocks base method.
func (m_2 *MockRuntime_PutFileServer) SendMsg(m interface{}) error {
	_ = "STUB: not implemented"
	return nil
}

// SendMsg indicates an expected call of SendMsg.
func (mr *MockRuntime_PutFileServerMockRecorder) SendMsg(m interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetHeader mocks base method.
func (m *MockRuntime_PutFileServer) SetHeader(arg0 metadata.MD) error {
	_ = "STUB: not implemented"
	return nil
}

// SetHeader indicates an expected call of SetHeader.
func (mr *MockRuntime_PutFileServerMockRecorder) SetHeader(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetTrailer mocks base method.
func (m *MockRuntime_PutFileServer) SetTrailer(arg0 metadata.MD) { _ = "STUB: not implemented"; return }

// SetTrailer indicates an expected call of SetTrailer.
func (mr *MockRuntime_PutFileServerMockRecorder) SetTrailer(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SubscribeTopicEvents mocks base method.
func (m *MockRuntimeClient) SubscribeTopicEvents(ctx context.Context, opts ...grpc.CallOption) (runtime.Runtime_SubscribeTopicEventsClient, error) {
	_ = "STUB: not implemented"
	return *new(runtime.Runtime_SubscribeTopicEventsClient), nil
}

// SubscribeTopicEvents indicates an expected call of SubscribeTopicEvents.
func (mr *MockRuntimeClientMockRecorder) SubscribeTopicEvents(ctx interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockRuntime_SubscribeTopicEventsClient is a mock of Runtime_SubscribeTopicEventsClient interface.
type MockRuntime_SubscribeTopicEventsClient struct {
	ctrl     *gomock.Controller
	recorder *MockRuntime_SubscribeTopicEventsClientMockRecorder
}

// MockRuntime_SubscribeTopicEventsClientMockRecorder is the mock recorder for MockRuntime_SubscribeTopicEventsClient.
type MockRuntime_SubscribeTopicEventsClientMockRecorder struct {
	mock *MockRuntime_SubscribeTopicEventsClient
}

// NewMockRuntime_SubscribeTopicEventsClient creates a new mock instance.
func NewMockRuntime_SubscribeTopicEventsClient(ctrl *gomock.Controller) *MockRuntime_SubscribeTopicEventsClient {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRuntime_SubscribeTopicEventsClient) EXPECT() *MockRuntime_SubscribeTopicEventsClientMockRecorder {
	_ = "STUB: not implemented"

	// CloseSend mocks base method.
	return nil
}

func (m *MockRuntime_SubscribeTopicEventsClient) CloseSend() error {
	_ = "STUB: not implemented"
	return nil
}

// CloseSend indicates an expected call of CloseSend.
func (mr *MockRuntime_SubscribeTopicEventsClientMockRecorder) CloseSend() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Context mocks base method.
func (m *MockRuntime_SubscribeTopicEventsClient) Context() context.Context {
	_ = "STUB: not implemented"
	return *new(context.Context)
}

// Context indicates an expected call of Context.
func (mr *MockRuntime_SubscribeTopicEventsClientMockRecorder) Context() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Header mocks base method.
func (m *MockRuntime_SubscribeTopicEventsClient) Header() (metadata.MD, error) {
	_ = "STUB: not implemented"
	return *new(metadata.MD), nil
}

// Header indicates an expected call of Header.
func (mr *MockRuntime_SubscribeTopicEventsClientMockRecorder) Header() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Recv mocks base method.
func (m *MockRuntime_SubscribeTopicEventsClient) Recv() (*runtime.SubscribeTopicEventsResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Recv indicates an expected call of Recv.
func (mr *MockRuntime_SubscribeTopicEventsClientMockRecorder) Recv() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// RecvMsg mocks base method.
func (m_2 *MockRuntime_SubscribeTopicEventsClient) RecvMsg(m interface{}) error {
	_ = "STUB: not implemented"
	return nil
}

// RecvMsg indicates an expected call of RecvMsg.
func (mr *MockRuntime_SubscribeTopicEventsClientMockRecorder) RecvMsg(m interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Send mocks base method.
func (m *MockRuntime_SubscribeTopicEventsClient) Send(arg0 *runtime.SubscribeTopicEventsRequest) error {
	_ = "STUB: not implemented"
	return nil
}

// Send indicates an expected call of Send.
func (mr *MockRuntime_SubscribeTopicEventsClientMockRecorder) Send(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SendMsg mocks base method.
func (m_2 *MockRuntime_SubscribeTopicEventsClient) SendMsg(m interface{}) error {
	_ = "STUB: not implemented"
	return nil
}

// SendMsg indicates an expected call of SendMsg.
func (mr *MockRuntime_SubscribeTopicEventsClientMockRecorder) SendMsg(m interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Trailer mocks base method.
func (m *MockRuntime_SubscribeTopicEventsClient) Trailer() metadata.MD {
	_ = "STUB: not implemented"
	return *new(metadata.MD)
}

// Trailer indicates an expected call of Trailer.
func (mr *MockRuntime_SubscribeTopicEventsClientMockRecorder) Trailer() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SubscribeTopicEvents mocks base method.
func (m *MockRuntimeServer) SubscribeTopicEvents(arg0 runtime.Runtime_SubscribeTopicEventsServer) error {
	_ = "STUB: not implemented"
	return nil
}

// SubscribeTopicEvents indicates an expected call of SubscribeTopicEvents.
func (mr *MockRuntimeServerMockRecorder) SubscribeTopicEvents(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockRuntime_SubscribeTopicEventsServer is a mock of Runtime_SubscribeTopicEventsServer interface.
type MockRuntime_SubscribeTopicEventsServer struct {
	ctrl     *gomock.Controller
	recorder *MockRuntime_SubscribeTopicEventsServerMockRecorder
}

// MockRuntime_SubscribeTopicEventsServerMockRecorder is the mock recorder for MockRuntime_SubscribeTopicEventsServer.
type MockRuntime_SubscribeTopicEventsServerMockRecorder struct {
	mock *MockRuntime_SubscribeTopicEventsServer
}

// NewMockRuntime_SubscribeTopicEventsServer creates a new mock instance.
func NewMockRuntime_SubscribeTopicEventsServer(ctrl *gomock.Controller) *MockRuntime_SubscribeTopicEventsServer {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRuntime_SubscribeTopicEventsServer) EXPECT() *MockRuntime_SubscribeTopicEventsServerMockRecorder {
	_ = "STUB: not implemented"

	// Context mocks base method.
	return nil
}

func (m *MockRuntime_SubscribeTopicEventsServer) Context() context.Context {
	_ = "STUB: not implemented"
	return *new(context.Context)
}

// Context indicates an expected call of Context.
func (mr *MockRuntime_SubscribeTopicEventsServerMockRecorder) Context() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Recv mocks base method.
func (m *MockRuntime_SubscribeTopicEventsServer) Recv() (*runtime.SubscribeTopicEventsRequest, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Recv indicates an expected call of Recv.
func (mr *MockRuntime_SubscribeTopicEventsServerMockRecorder) Recv() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// RecvMsg mocks base method.
func (m_2 *MockRuntime_SubscribeTopicEventsServer) RecvMsg(m interface{}) error {
	_ = "STUB: not implemented"
	return nil
}

// RecvMsg indicates an expected call of RecvMsg.
func (mr *MockRuntime_SubscribeTopicEventsServerMockRecorder) RecvMsg(m interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Send mocks base method.
func (m *MockRuntime_SubscribeTopicEventsServer) Send(arg0 *runtime.SubscribeTopicEventsResponse) error {
	_ = "STUB: not implemented"
	return nil
}

// Send indicates an expected call of Send.
func (mr *MockRuntime_SubscribeTopicEventsServerMockRecorder) Send(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SendHeader mocks base method.
func (m *MockRuntime_SubscribeTopicEventsServer) SendHeader(arg0 metadata.MD) error {
	_ = "STUB: not implemented"
	return nil
}

// SendHeader indicates an expected call of SendHeader.
func (mr *MockRuntime_SubscribeTopicEventsServerMockRecorder) SendHeader(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SendMsg mocks base method.
func (m_2 *MockRuntime_SubscribeTopicEventsServer) SendMsg(m interface{}) error {
	_ = "STUB: not implemented"
	return nil
}

// SendMsg indicates an expected call of SendMsg.
func (mr *MockRuntime_SubscribeTopicEventsServerMockRecorder) SendMsg(m interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetHeader mocks base method.
func (m *MockRuntime_SubscribeTopicEventsServer) SetHeader(arg0 metadata.MD) error {
	_ = "STUB: not implemented"
	return nil
}

// SetHeader indicates an expected call of SetHeader.
func (mr *MockRuntime_SubscribeTopicEventsServerMockRecorder) SetHeader(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetTrailer mocks base method.
func (m *MockRuntime_SubscribeTopicEventsServer) SetTrailer(arg0 metadata.MD) {
	_ = "STUB: not implemented"
	return
}

// SetTrailer indicates an expected call of SetTrailer.
func (mr *MockRuntime_SubscribeTopicEventsServerMockRecorder) SetTrailer(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
