// Code generated by MockGen. DO NOT EDIT.
// Source: lock_store.go

// Package mock_lock is a generated GoMock package.
package mock_lock

import (
	context "context"

	gomock "github.com/golang/mock/gomock"

	lock "mosn.io/layotto/components/lock"
)

// MockLockStore is a mock of LockStore interface.
type MockLockStore struct {
	ctrl     *gomock.Controller
	recorder *MockLockStoreMockRecorder
}

// MockLockStoreMockRecorder is the mock recorder for MockLockStore.
type MockLockStoreMockRecorder struct {
	mock *MockLockStore
}

// NewMockLockStore creates a new mock instance.
func NewMockLockStore(ctrl *gomock.Controller) *MockLockStore {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLockStore) EXPECT() *MockLockStoreMockRecorder {
	_ = "STUB: not implemented"

	// Features mocks base method.
	return nil
}

func (m *MockLockStore) Features() []lock.Feature { _ = "STUB: not implemented"; return nil }

// Features indicates an expected call of Features.
func (mr *MockLockStoreMockRecorder) Features() *gomock.Call { _ = "STUB: not implemented"; return nil }

// Init mocks base method.
func (m *MockLockStore) Init(metadata lock.Metadata) error { _ = "STUB: not implemented"; return nil }

// Init indicates an expected call of Init.
func (mr *MockLockStoreMockRecorder) Init(metadata interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// LockKeepAlive mocks base method.
func (m *MockLockStore) LockKeepAlive(arg0 context.Context, arg1 *lock.LockKeepAliveRequest) (*lock.LockKeepAliveResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// LockKeepAlive indicates an expected call of LockKeepAlive.
func (mr *MockLockStoreMockRecorder) LockKeepAlive(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// TryLock mocks base method.
func (m *MockLockStore) TryLock(ctx context.Context, req *lock.TryLockRequest) (*lock.TryLockResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// TryLock indicates an expected call of TryLock.
func (mr *MockLockStoreMockRecorder) TryLock(ctx, req interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Unlock mocks base method.
func (m *MockLockStore) Unlock(ctx context.Context, req *lock.UnlockRequest) (*lock.UnlockResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Unlock indicates an expected call of Unlock.
func (mr *MockLockStoreMockRecorder) Unlock(ctx, req interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
