// Code generated by github.com/layotto/protoc-gen-p6 .

// Copyright 2021 Layotto Authors
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package runtime

import (
	cryption "mosn.io/layotto/components/cryption"
	email "mosn.io/layotto/components/email"
	phone "mosn.io/layotto/components/phone"
	sms "mosn.io/layotto/components/sms"
)

type extensionComponents struct {
	cryptionService map[string]cryption.CryptionService

	emailService map[string]email.EmailService

	phoneCallService map[string]phone.PhoneCallService

	smsService map[string]sms.SmsService
}

func newExtensionComponents() *extensionComponents { _ = "STUB: not implemented"; return nil }

func (m *MosnRuntime) initCryptionService(factorys ...*cryption.Factory) error {
	_ = "STUB: not implemented"
	return nil
}

// 1. register all implementation

// 2. loop initializing

// 2.1. create the component

//inject secret to component

// 2.2. init

func (m *MosnRuntime) initEmailService(factorys ...*email.Factory) error {
	_ = "STUB: not implemented"
	return nil
}

// 1. register all implementation

// 2. loop initializing

// 2.1. create the component

//inject secret to component

// 2.2. init

func (m *MosnRuntime) initPhoneCallService(factorys ...*phone.Factory) error {
	_ = "STUB: not implemented"
	return nil
}

// 1. register all implementation

// 2. loop initializing

// 2.1. create the component

//inject secret to component

// 2.2. init

func (m *MosnRuntime) initSmsService(factorys ...*sms.Factory) error {
	_ = "STUB: not implemented"
	return nil
}

// 1. register all implementation

// 2. loop initializing

// 2.1. create the component

//inject secret to component

// 2.2. init

func (m *MosnRuntime) initExtensionComponent(s services) error {
	_ = "STUB: not implemented"
	return nil
}
