// Code generated by github.com/seeflood/protoc-gen-p6 .

// Copyright 2021 Layotto Authors
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package aws

import (
	"context"
	"sync"

	"mosn.io/layotto/components/pkg/actuators"

	"github.com/aws/aws-sdk-go/service/kms"

	log "mosn.io/layotto/kit/logger"

	"mosn.io/layotto/components/cryption"
)

const (
	componentName = "kms-aws"
)

var (
	once               sync.Once
	readinessIndicator *actuators.HealthIndicator
	livenessIndicator  *actuators.HealthIndicator
)

func init() {
	readinessIndicator = actuators.NewHealthIndicator()
	livenessIndicator = actuators.NewHealthIndicator()
}

type cy struct {
	client *kms.KMS
	keyID  string
	log    log.Logger
}

func NewCryption() cryption.CryptionService {
	_ = "STUB: not implemented"
	return *new(cryption.CryptionService)
}

func (k *cy) OnLogLevelChanged(outputLevel log.LogLevel) { _ = "STUB: not implemented"; return }

func (k *cy) Init(ctx context.Context, conf *cryption.Config) error {
	_ = "STUB: not implemented"
	return nil
}

func (k *cy) Decrypt(ctx context.Context, request *cryption.DecryptRequest) (*cryption.DecryptResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (k *cy) Encrypt(ctx context.Context, request *cryption.EncryptRequest) (*cryption.EncryptResponse, error) {
	_ = "STUB: not implemented"
	// if keyId specified, use request KeyId
	return nil, nil
}
