// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.17.3
// source: runtime.proto

package runtime

import (
	context "context"

	grpc "google.golang.org/grpc"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RuntimeClient is the client API for Runtime service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RuntimeClient interface {
	//SayHello used for test
	SayHello(ctx context.Context, in *SayHelloRequest, opts ...grpc.CallOption) (*SayHelloResponse, error)
	// InvokeService do rpc calls
	InvokeService(ctx context.Context, in *InvokeServiceRequest, opts ...grpc.CallOption) (*InvokeResponse, error)
	// GetConfiguration gets configuration from configuration store.
	GetConfiguration(ctx context.Context, in *GetConfigurationRequest, opts ...grpc.CallOption) (*GetConfigurationResponse, error)
	// SaveConfiguration saves configuration into configuration store.
	SaveConfiguration(ctx context.Context, in *SaveConfigurationRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// DeleteConfiguration deletes configuration from configuration store.
	DeleteConfiguration(ctx context.Context, in *DeleteConfigurationRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// SubscribeConfiguration gets configuration from configuration store and subscribe the updates.
	SubscribeConfiguration(ctx context.Context, opts ...grpc.CallOption) (Runtime_SubscribeConfigurationClient, error)
	// Distributed Lock API
	// A non-blocking method trying to get a lock with ttl.
	TryLock(ctx context.Context, in *TryLockRequest, opts ...grpc.CallOption) (*TryLockResponse, error)
	// A method trying to unlock.
	Unlock(ctx context.Context, in *UnlockRequest, opts ...grpc.CallOption) (*UnlockResponse, error)
	// A method used to support lease renewal for distributed lock.
	LockKeepAlive(ctx context.Context, in *LockKeepAliveRequest, opts ...grpc.CallOption) (*LockKeepAliveResponse, error)
	// Sequencer API
	// Get next unique id with some auto-increment guarantee
	GetNextId(ctx context.Context, in *GetNextIdRequest, opts ...grpc.CallOption) (*GetNextIdResponse, error)
	// Gets the state for a specific key.
	GetState(ctx context.Context, in *GetStateRequest, opts ...grpc.CallOption) (*GetStateResponse, error)
	// Gets a bulk of state items for a list of keys
	GetBulkState(ctx context.Context, in *GetBulkStateRequest, opts ...grpc.CallOption) (*GetBulkStateResponse, error)
	// Saves an array of state objects
	SaveState(ctx context.Context, in *SaveStateRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Deletes the state for a specific key.
	DeleteState(ctx context.Context, in *DeleteStateRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Deletes a bulk of state items for a list of keys
	DeleteBulkState(ctx context.Context, in *DeleteBulkStateRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Executes transactions for a specified store
	ExecuteStateTransaction(ctx context.Context, in *ExecuteStateTransactionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Publishes events to the specific topic
	PublishEvent(ctx context.Context, in *PublishEventRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// SubscribeTopicEvents subscribes to a PubSub topic and receives topic
	// events from it.
	SubscribeTopicEvents(ctx context.Context, opts ...grpc.CallOption) (Runtime_SubscribeTopicEventsClient, error)
	// Get file with stream
	GetFile(ctx context.Context, in *GetFileRequest, opts ...grpc.CallOption) (Runtime_GetFileClient, error)
	// Put file with stream
	PutFile(ctx context.Context, opts ...grpc.CallOption) (Runtime_PutFileClient, error)
	// List all files
	ListFile(ctx context.Context, in *ListFileRequest, opts ...grpc.CallOption) (*ListFileResp, error)
	// Delete specific file
	DelFile(ctx context.Context, in *DelFileRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Get file meta data, if file not exist,return code.NotFound error
	GetFileMeta(ctx context.Context, in *GetFileMetaRequest, opts ...grpc.CallOption) (*GetFileMetaResponse, error)
	// Invokes binding data to specific output bindings
	InvokeBinding(ctx context.Context, in *InvokeBindingRequest, opts ...grpc.CallOption) (*InvokeBindingResponse, error)
	// Gets secrets from secret stores.
	GetSecret(ctx context.Context, in *GetSecretRequest, opts ...grpc.CallOption) (*GetSecretResponse, error)
	// Gets a bulk of secrets
	GetBulkSecret(ctx context.Context, in *GetBulkSecretRequest, opts ...grpc.CallOption) (*GetBulkSecretResponse, error)
}

type runtimeClient struct {
	cc grpc.ClientConnInterface
}

func NewRuntimeClient(cc grpc.ClientConnInterface) RuntimeClient {
	_ = "STUB: not implemented"
	return *new(RuntimeClient)
}

func (c *runtimeClient) SayHello(ctx context.Context, in *SayHelloRequest, opts ...grpc.CallOption) (*SayHelloResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *runtimeClient) InvokeService(ctx context.Context, in *InvokeServiceRequest, opts ...grpc.CallOption) (*InvokeResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *runtimeClient) GetConfiguration(ctx context.Context, in *GetConfigurationRequest, opts ...grpc.CallOption) (*GetConfigurationResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *runtimeClient) SaveConfiguration(ctx context.Context, in *SaveConfigurationRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *runtimeClient) DeleteConfiguration(ctx context.Context, in *DeleteConfigurationRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *runtimeClient) SubscribeConfiguration(ctx context.Context, opts ...grpc.CallOption) (Runtime_SubscribeConfigurationClient, error) {
	_ = "STUB: not implemented"
	return *new(Runtime_SubscribeConfigurationClient), nil
}

type Runtime_SubscribeConfigurationClient interface {
	Send(*SubscribeConfigurationRequest) error
	Recv() (*SubscribeConfigurationResponse, error)
	grpc.ClientStream
}

type runtimeSubscribeConfigurationClient struct {
	grpc.ClientStream
}

func (x *runtimeSubscribeConfigurationClient) Send(m *SubscribeConfigurationRequest) error {
	_ = "STUB: not implemented"
	return nil
}

func (x *runtimeSubscribeConfigurationClient) Recv() (*SubscribeConfigurationResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *runtimeClient) TryLock(ctx context.Context, in *TryLockRequest, opts ...grpc.CallOption) (*TryLockResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *runtimeClient) Unlock(ctx context.Context, in *UnlockRequest, opts ...grpc.CallOption) (*UnlockResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *runtimeClient) LockKeepAlive(ctx context.Context, in *LockKeepAliveRequest, opts ...grpc.CallOption) (*LockKeepAliveResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *runtimeClient) GetNextId(ctx context.Context, in *GetNextIdRequest, opts ...grpc.CallOption) (*GetNextIdResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *runtimeClient) GetState(ctx context.Context, in *GetStateRequest, opts ...grpc.CallOption) (*GetStateResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *runtimeClient) GetBulkState(ctx context.Context, in *GetBulkStateRequest, opts ...grpc.CallOption) (*GetBulkStateResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *runtimeClient) SaveState(ctx context.Context, in *SaveStateRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *runtimeClient) DeleteState(ctx context.Context, in *DeleteStateRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *runtimeClient) DeleteBulkState(ctx context.Context, in *DeleteBulkStateRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *runtimeClient) ExecuteStateTransaction(ctx context.Context, in *ExecuteStateTransactionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *runtimeClient) PublishEvent(ctx context.Context, in *PublishEventRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *runtimeClient) SubscribeTopicEvents(ctx context.Context, opts ...grpc.CallOption) (Runtime_SubscribeTopicEventsClient, error) {
	_ = "STUB: not implemented"
	return *new(Runtime_SubscribeTopicEventsClient), nil
}

type Runtime_SubscribeTopicEventsClient interface {
	Send(*SubscribeTopicEventsRequest) error
	Recv() (*SubscribeTopicEventsResponse, error)
	grpc.ClientStream
}

type runtimeSubscribeTopicEventsClient struct {
	grpc.ClientStream
}

func (x *runtimeSubscribeTopicEventsClient) Send(m *SubscribeTopicEventsRequest) error {
	_ = "STUB: not implemented"
	return nil
}

func (x *runtimeSubscribeTopicEventsClient) Recv() (*SubscribeTopicEventsResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *runtimeClient) GetFile(ctx context.Context, in *GetFileRequest, opts ...grpc.CallOption) (Runtime_GetFileClient, error) {
	_ = "STUB: not implemented"
	return *new(Runtime_GetFileClient), nil
}

type Runtime_GetFileClient interface {
	Recv() (*GetFileResponse, error)
	grpc.ClientStream
}

type runtimeGetFileClient struct {
	grpc.ClientStream
}

func (x *runtimeGetFileClient) Recv() (*GetFileResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *runtimeClient) PutFile(ctx context.Context, opts ...grpc.CallOption) (Runtime_PutFileClient, error) {
	_ = "STUB: not implemented"
	return *new(Runtime_PutFileClient), nil
}

type Runtime_PutFileClient interface {
	Send(*PutFileRequest) error
	CloseAndRecv() (*emptypb.Empty, error)
	grpc.ClientStream
}

type runtimePutFileClient struct {
	grpc.ClientStream
}

func (x *runtimePutFileClient) Send(m *PutFileRequest) error { _ = "STUB: not implemented"; return nil }

func (x *runtimePutFileClient) CloseAndRecv() (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *runtimeClient) ListFile(ctx context.Context, in *ListFileRequest, opts ...grpc.CallOption) (*ListFileResp, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *runtimeClient) DelFile(ctx context.Context, in *DelFileRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *runtimeClient) GetFileMeta(ctx context.Context, in *GetFileMetaRequest, opts ...grpc.CallOption) (*GetFileMetaResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *runtimeClient) InvokeBinding(ctx context.Context, in *InvokeBindingRequest, opts ...grpc.CallOption) (*InvokeBindingResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *runtimeClient) GetSecret(ctx context.Context, in *GetSecretRequest, opts ...grpc.CallOption) (*GetSecretResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *runtimeClient) GetBulkSecret(ctx context.Context, in *GetBulkSecretRequest, opts ...grpc.CallOption) (*GetBulkSecretResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// RuntimeServer is the server API for Runtime service.
// All implementations should embed UnimplementedRuntimeServer
// for forward compatibility
type RuntimeServer interface {
	//SayHello used for test
	SayHello(context.Context, *SayHelloRequest) (*SayHelloResponse, error)
	// InvokeService do rpc calls
	InvokeService(context.Context, *InvokeServiceRequest) (*InvokeResponse, error)
	// GetConfiguration gets configuration from configuration store.
	GetConfiguration(context.Context, *GetConfigurationRequest) (*GetConfigurationResponse, error)
	// SaveConfiguration saves configuration into configuration store.
	SaveConfiguration(context.Context, *SaveConfigurationRequest) (*emptypb.Empty, error)
	// DeleteConfiguration deletes configuration from configuration store.
	DeleteConfiguration(context.Context, *DeleteConfigurationRequest) (*emptypb.Empty, error)
	// SubscribeConfiguration gets configuration from configuration store and subscribe the updates.
	SubscribeConfiguration(Runtime_SubscribeConfigurationServer) error
	// Distributed Lock API
	// A non-blocking method trying to get a lock with ttl.
	TryLock(context.Context, *TryLockRequest) (*TryLockResponse, error)
	// A method trying to unlock.
	Unlock(context.Context, *UnlockRequest) (*UnlockResponse, error)
	// A method used to support lease renewal for distributed lock.
	LockKeepAlive(context.Context, *LockKeepAliveRequest) (*LockKeepAliveResponse, error)
	// Sequencer API
	// Get next unique id with some auto-increment guarantee
	GetNextId(context.Context, *GetNextIdRequest) (*GetNextIdResponse, error)
	// Gets the state for a specific key.
	GetState(context.Context, *GetStateRequest) (*GetStateResponse, error)
	// Gets a bulk of state items for a list of keys
	GetBulkState(context.Context, *GetBulkStateRequest) (*GetBulkStateResponse, error)
	// Saves an array of state objects
	SaveState(context.Context, *SaveStateRequest) (*emptypb.Empty, error)
	// Deletes the state for a specific key.
	DeleteState(context.Context, *DeleteStateRequest) (*emptypb.Empty, error)
	// Deletes a bulk of state items for a list of keys
	DeleteBulkState(context.Context, *DeleteBulkStateRequest) (*emptypb.Empty, error)
	// Executes transactions for a specified store
	ExecuteStateTransaction(context.Context, *ExecuteStateTransactionRequest) (*emptypb.Empty, error)
	// Publishes events to the specific topic
	PublishEvent(context.Context, *PublishEventRequest) (*emptypb.Empty, error)
	// SubscribeTopicEvents subscribes to a PubSub topic and receives topic
	// events from it.
	SubscribeTopicEvents(Runtime_SubscribeTopicEventsServer) error
	// Get file with stream
	GetFile(*GetFileRequest, Runtime_GetFileServer) error
	// Put file with stream
	PutFile(Runtime_PutFileServer) error
	// List all files
	ListFile(context.Context, *ListFileRequest) (*ListFileResp, error)
	// Delete specific file
	DelFile(context.Context, *DelFileRequest) (*emptypb.Empty, error)
	// Get file meta data, if file not exist,return code.NotFound error
	GetFileMeta(context.Context, *GetFileMetaRequest) (*GetFileMetaResponse, error)
	// Invokes binding data to specific output bindings
	InvokeBinding(context.Context, *InvokeBindingRequest) (*InvokeBindingResponse, error)
	// Gets secrets from secret stores.
	GetSecret(context.Context, *GetSecretRequest) (*GetSecretResponse, error)
	// Gets a bulk of secrets
	GetBulkSecret(context.Context, *GetBulkSecretRequest) (*GetBulkSecretResponse, error)
}

// UnimplementedRuntimeServer should be embedded to have forward compatible implementations.
type UnimplementedRuntimeServer struct {
}

func (UnimplementedRuntimeServer) SayHello(context.Context, *SayHelloRequest) (*SayHelloResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedRuntimeServer) InvokeService(context.Context, *InvokeServiceRequest) (*InvokeResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedRuntimeServer) GetConfiguration(context.Context, *GetConfigurationRequest) (*GetConfigurationResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedRuntimeServer) SaveConfiguration(context.Context, *SaveConfigurationRequest) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedRuntimeServer) DeleteConfiguration(context.Context, *DeleteConfigurationRequest) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedRuntimeServer) SubscribeConfiguration(Runtime_SubscribeConfigurationServer) error {
	_ = "STUB: not implemented"
	return nil
}

func (UnimplementedRuntimeServer) TryLock(context.Context, *TryLockRequest) (*TryLockResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedRuntimeServer) Unlock(context.Context, *UnlockRequest) (*UnlockResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedRuntimeServer) LockKeepAlive(context.Context, *LockKeepAliveRequest) (*LockKeepAliveResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedRuntimeServer) GetNextId(context.Context, *GetNextIdRequest) (*GetNextIdResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedRuntimeServer) GetState(context.Context, *GetStateRequest) (*GetStateResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedRuntimeServer) GetBulkState(context.Context, *GetBulkStateRequest) (*GetBulkStateResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedRuntimeServer) SaveState(context.Context, *SaveStateRequest) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedRuntimeServer) DeleteState(context.Context, *DeleteStateRequest) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedRuntimeServer) DeleteBulkState(context.Context, *DeleteBulkStateRequest) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedRuntimeServer) ExecuteStateTransaction(context.Context, *ExecuteStateTransactionRequest) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedRuntimeServer) PublishEvent(context.Context, *PublishEventRequest) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedRuntimeServer) SubscribeTopicEvents(Runtime_SubscribeTopicEventsServer) error {
	_ = "STUB: not implemented"
	return nil
}

func (UnimplementedRuntimeServer) GetFile(*GetFileRequest, Runtime_GetFileServer) error {
	_ = "STUB: not implemented"
	return nil
}

func (UnimplementedRuntimeServer) PutFile(Runtime_PutFileServer) error {
	_ = "STUB: not implemented"
	return nil
}

func (UnimplementedRuntimeServer) ListFile(context.Context, *ListFileRequest) (*ListFileResp, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedRuntimeServer) DelFile(context.Context, *DelFileRequest) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedRuntimeServer) GetFileMeta(context.Context, *GetFileMetaRequest) (*GetFileMetaResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedRuntimeServer) InvokeBinding(context.Context, *InvokeBindingRequest) (*InvokeBindingResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedRuntimeServer) GetSecret(context.Context, *GetSecretRequest) (*GetSecretResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedRuntimeServer) GetBulkSecret(context.Context, *GetBulkSecretRequest) (*GetBulkSecretResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnsafeRuntimeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RuntimeServer will
// result in compilation errors.
type UnsafeRuntimeServer interface {
	mustEmbedUnimplementedRuntimeServer()
}

func RegisterRuntimeServer(s grpc.ServiceRegistrar, srv RuntimeServer) {
	_ = "STUB: not implemented"
	return
}

func _Runtime_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _Runtime_InvokeService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _Runtime_GetConfiguration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _Runtime_SaveConfiguration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _Runtime_DeleteConfiguration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _Runtime_SubscribeConfiguration_Handler(srv interface{}, stream grpc.ServerStream) error {
	_ = "STUB: not implemented"
	return nil
}

type Runtime_SubscribeConfigurationServer interface {
	Send(*SubscribeConfigurationResponse) error
	Recv() (*SubscribeConfigurationRequest, error)
	grpc.ServerStream
}

type runtimeSubscribeConfigurationServer struct {
	grpc.ServerStream
}

func (x *runtimeSubscribeConfigurationServer) Send(m *SubscribeConfigurationResponse) error {
	_ = "STUB: not implemented"
	return nil
}

func (x *runtimeSubscribeConfigurationServer) Recv() (*SubscribeConfigurationRequest, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _Runtime_TryLock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _Runtime_Unlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _Runtime_LockKeepAlive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _Runtime_GetNextId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _Runtime_GetState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _Runtime_GetBulkState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _Runtime_SaveState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _Runtime_DeleteState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _Runtime_DeleteBulkState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _Runtime_ExecuteStateTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _Runtime_PublishEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _Runtime_SubscribeTopicEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	_ = "STUB: not implemented"
	return nil
}

type Runtime_SubscribeTopicEventsServer interface {
	Send(*SubscribeTopicEventsResponse) error
	Recv() (*SubscribeTopicEventsRequest, error)
	grpc.ServerStream
}

type runtimeSubscribeTopicEventsServer struct {
	grpc.ServerStream
}

func (x *runtimeSubscribeTopicEventsServer) Send(m *SubscribeTopicEventsResponse) error {
	_ = "STUB: not implemented"
	return nil
}

func (x *runtimeSubscribeTopicEventsServer) Recv() (*SubscribeTopicEventsRequest, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _Runtime_GetFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	_ = "STUB: not implemented"
	return nil
}

type Runtime_GetFileServer interface {
	Send(*GetFileResponse) error
	grpc.ServerStream
}

type runtimeGetFileServer struct {
	grpc.ServerStream
}

func (x *runtimeGetFileServer) Send(m *GetFileResponse) error {
	_ = "STUB: not implemented"
	return nil
}

func _Runtime_PutFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	_ = "STUB: not implemented"
	return nil
}

type Runtime_PutFileServer interface {
	SendAndClose(*emptypb.Empty) error
	Recv() (*PutFileRequest, error)
	grpc.ServerStream
}

type runtimePutFileServer struct {
	grpc.ServerStream
}

func (x *runtimePutFileServer) SendAndClose(m *emptypb.Empty) error {
	_ = "STUB: not implemented"
	return nil
}

func (x *runtimePutFileServer) Recv() (*PutFileRequest, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _Runtime_ListFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _Runtime_DelFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _Runtime_GetFileMeta_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _Runtime_InvokeBinding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _Runtime_GetSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _Runtime_GetBulkSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Runtime_ServiceDesc is the grpc.ServiceDesc for Runtime service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Runtime_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "spec.proto.runtime.v1.Runtime",
	HandlerType: (*RuntimeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Runtime_SayHello_Handler,
		},
		{
			MethodName: "InvokeService",
			Handler:    _Runtime_InvokeService_Handler,
		},
		{
			MethodName: "GetConfiguration",
			Handler:    _Runtime_GetConfiguration_Handler,
		},
		{
			MethodName: "SaveConfiguration",
			Handler:    _Runtime_SaveConfiguration_Handler,
		},
		{
			MethodName: "DeleteConfiguration",
			Handler:    _Runtime_DeleteConfiguration_Handler,
		},
		{
			MethodName: "TryLock",
			Handler:    _Runtime_TryLock_Handler,
		},
		{
			MethodName: "Unlock",
			Handler:    _Runtime_Unlock_Handler,
		},
		{
			MethodName: "LockKeepAlive",
			Handler:    _Runtime_LockKeepAlive_Handler,
		},
		{
			MethodName: "GetNextId",
			Handler:    _Runtime_GetNextId_Handler,
		},
		{
			MethodName: "GetState",
			Handler:    _Runtime_GetState_Handler,
		},
		{
			MethodName: "GetBulkState",
			Handler:    _Runtime_GetBulkState_Handler,
		},
		{
			MethodName: "SaveState",
			Handler:    _Runtime_SaveState_Handler,
		},
		{
			MethodName: "DeleteState",
			Handler:    _Runtime_DeleteState_Handler,
		},
		{
			MethodName: "DeleteBulkState",
			Handler:    _Runtime_DeleteBulkState_Handler,
		},
		{
			MethodName: "ExecuteStateTransaction",
			Handler:    _Runtime_ExecuteStateTransaction_Handler,
		},
		{
			MethodName: "PublishEvent",
			Handler:    _Runtime_PublishEvent_Handler,
		},
		{
			MethodName: "ListFile",
			Handler:    _Runtime_ListFile_Handler,
		},
		{
			MethodName: "DelFile",
			Handler:    _Runtime_DelFile_Handler,
		},
		{
			MethodName: "GetFileMeta",
			Handler:    _Runtime_GetFileMeta_Handler,
		},
		{
			MethodName: "InvokeBinding",
			Handler:    _Runtime_InvokeBinding_Handler,
		},
		{
			MethodName: "GetSecret",
			Handler:    _Runtime_GetSecret_Handler,
		},
		{
			MethodName: "GetBulkSecret",
			Handler:    _Runtime_GetBulkSecret_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeConfiguration",
			Handler:       _Runtime_SubscribeConfiguration_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "SubscribeTopicEvents",
			Handler:       _Runtime_SubscribeTopicEvents_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "GetFile",
			Handler:       _Runtime_GetFile_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "PutFile",
			Handler:       _Runtime_PutFile_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "runtime.proto",
}
