// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/wasm/exports.go

// Package mock_wasm is a generated GoMock package.
package mock_wasm

import (
	gomock "github.com/golang/mock/gomock"
	v1 "mosn.io/proxy-wasm-go-host/proxywasm/v1"
)

// MockExports is a mock of Exports interface.
type MockExports struct {
	ctrl     *gomock.Controller
	recorder *MockExportsMockRecorder
}

// MockExportsMockRecorder is the mock recorder for MockExports.
type MockExportsMockRecorder struct {
	mock *MockExports
}

// NewMockExports creates a new mock instance.
func NewMockExports(ctrl *gomock.Controller) *MockExports { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExports) EXPECT() *MockExportsMockRecorder {
	_ = "STUB: not implemented"

	// ProxyGetID mocks base method.
	return nil
}

func (m *MockExports) ProxyGetID() (string, error) { _ = "STUB: not implemented"; return "", nil }

// ProxyGetID indicates an expected call of ProxyGetID.
func (mr *MockExportsMockRecorder) ProxyGetID() *gomock.Call { _ = "STUB: not implemented"; return nil }

// ProxyOnConfigure mocks base method.
func (m *MockExports) ProxyOnConfigure(rootContextID, pluginConfigurationSize int32) (int32, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

// ProxyOnConfigure indicates an expected call of ProxyOnConfigure.
func (mr *MockExportsMockRecorder) ProxyOnConfigure(rootContextID, pluginConfigurationSize interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ProxyOnContextCreate mocks base method.
func (m *MockExports) ProxyOnContextCreate(contextID, parentContextID int32) error {
	_ = "STUB: not implemented"
	return nil
}

// ProxyOnContextCreate indicates an expected call of ProxyOnContextCreate.
func (mr *MockExportsMockRecorder) ProxyOnContextCreate(contextID, parentContextID interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ProxyOnDelete mocks base method.
func (m *MockExports) ProxyOnDelete(contextID int32) error { _ = "STUB: not implemented"; return nil }

// ProxyOnDelete indicates an expected call of ProxyOnDelete.
func (mr *MockExportsMockRecorder) ProxyOnDelete(contextID interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ProxyOnDone mocks base method.
func (m *MockExports) ProxyOnDone(contextID int32) (int32, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

// ProxyOnDone indicates an expected call of ProxyOnDone.
func (mr *MockExportsMockRecorder) ProxyOnDone(contextID interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ProxyOnDownstreamConnectionClose mocks base method.
func (m *MockExports) ProxyOnDownstreamConnectionClose(contextID, closeType int32) error {
	_ = "STUB: not implemented"
	return nil
}

// ProxyOnDownstreamConnectionClose indicates an expected call of ProxyOnDownstreamConnectionClose.
func (mr *MockExportsMockRecorder) ProxyOnDownstreamConnectionClose(contextID, closeType interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ProxyOnDownstreamData mocks base method.
func (m *MockExports) ProxyOnDownstreamData(contextID, dataLength, endOfStream int32) (v1.Action, error) {
	_ = "STUB: not implemented"
	return *new(v1.Action), nil
}

// ProxyOnDownstreamData indicates an expected call of ProxyOnDownstreamData.
func (mr *MockExportsMockRecorder) ProxyOnDownstreamData(contextID, dataLength, endOfStream interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ProxyOnGrpcCallClose mocks base method.
func (m *MockExports) ProxyOnGrpcCallClose(contextID, calloutID, statusCode int32) error {
	_ = "STUB: not implemented"
	return nil
}

// ProxyOnGrpcCallClose indicates an expected call of ProxyOnGrpcCallClose.
func (mr *MockExportsMockRecorder) ProxyOnGrpcCallClose(contextID, calloutID, statusCode interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ProxyOnGrpcCallResponseHeaderMetadata mocks base method.
func (m *MockExports) ProxyOnGrpcCallResponseHeaderMetadata(contextID, calloutID, nElements int32) error {
	_ = "STUB: not implemented"
	return nil
}

// ProxyOnGrpcCallResponseHeaderMetadata indicates an expected call of ProxyOnGrpcCallResponseHeaderMetadata.
func (mr *MockExportsMockRecorder) ProxyOnGrpcCallResponseHeaderMetadata(contextID, calloutID, nElements interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ProxyOnGrpcCallResponseMessage mocks base method.
func (m *MockExports) ProxyOnGrpcCallResponseMessage(contextID, calloutID, msgSize int32) error {
	_ = "STUB: not implemented"
	return nil
}

// ProxyOnGrpcCallResponseMessage indicates an expected call of ProxyOnGrpcCallResponseMessage.
func (mr *MockExportsMockRecorder) ProxyOnGrpcCallResponseMessage(contextID, calloutID, msgSize interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ProxyOnGrpcCallResponseTrailerMetadata mocks base method.
func (m *MockExports) ProxyOnGrpcCallResponseTrailerMetadata(contextID, calloutID, nElements int32) error {
	_ = "STUB: not implemented"
	return nil
}

// ProxyOnGrpcCallResponseTrailerMetadata indicates an expected call of ProxyOnGrpcCallResponseTrailerMetadata.
func (mr *MockExportsMockRecorder) ProxyOnGrpcCallResponseTrailerMetadata(contextID, calloutID, nElements interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ProxyOnHttpCallResponse mocks base method.
func (m *MockExports) ProxyOnHttpCallResponse(contextID, token, headers, bodySize, trailers int32) error {
	_ = "STUB: not implemented"
	return nil
}

// ProxyOnHttpCallResponse indicates an expected call of ProxyOnHttpCallResponse.
func (mr *MockExportsMockRecorder) ProxyOnHttpCallResponse(contextID, token, headers, bodySize, trailers interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ProxyOnLog mocks base method.
func (m *MockExports) ProxyOnLog(contextID int32) error { _ = "STUB: not implemented"; return nil }

// ProxyOnLog indicates an expected call of ProxyOnLog.
func (mr *MockExportsMockRecorder) ProxyOnLog(contextID interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ProxyOnMemoryAllocate mocks base method.
func (m *MockExports) ProxyOnMemoryAllocate(size int32) (int32, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

// ProxyOnMemoryAllocate indicates an expected call of ProxyOnMemoryAllocate.
func (mr *MockExportsMockRecorder) ProxyOnMemoryAllocate(size interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ProxyOnNewConnection mocks base method.
func (m *MockExports) ProxyOnNewConnection(contextID int32) (v1.Action, error) {
	_ = "STUB: not implemented"
	return *new(v1.Action), nil
}

// ProxyOnNewConnection indicates an expected call of ProxyOnNewConnection.
func (mr *MockExportsMockRecorder) ProxyOnNewConnection(contextID interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ProxyOnQueueReady mocks base method.
func (m *MockExports) ProxyOnQueueReady(rootContextID, token int32) error {
	_ = "STUB: not implemented"
	return nil
}

// ProxyOnQueueReady indicates an expected call of ProxyOnQueueReady.
func (mr *MockExportsMockRecorder) ProxyOnQueueReady(rootContextID, token interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ProxyOnRequestBody mocks base method.
func (m *MockExports) ProxyOnRequestBody(contextID, bodyBufferLength, endOfStream int32) (v1.Action, error) {
	_ = "STUB: not implemented"
	return *new(v1.Action), nil
}

// ProxyOnRequestBody indicates an expected call of ProxyOnRequestBody.
func (mr *MockExportsMockRecorder) ProxyOnRequestBody(contextID, bodyBufferLength, endOfStream interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ProxyOnRequestHeaders mocks base method.
func (m *MockExports) ProxyOnRequestHeaders(contextID, headers, endOfStream int32) (v1.Action, error) {
	_ = "STUB: not implemented"
	return *new(v1.Action), nil
}

// ProxyOnRequestHeaders indicates an expected call of ProxyOnRequestHeaders.
func (mr *MockExportsMockRecorder) ProxyOnRequestHeaders(contextID, headers, endOfStream interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ProxyOnRequestMetadata mocks base method.
func (m *MockExports) ProxyOnRequestMetadata(contextID, nElements int32) (v1.Action, error) {
	_ = "STUB: not implemented"
	return *new(v1.Action), nil
}

// ProxyOnRequestMetadata indicates an expected call of ProxyOnRequestMetadata.
func (mr *MockExportsMockRecorder) ProxyOnRequestMetadata(contextID, nElements interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ProxyOnRequestTrailers mocks base method.
func (m *MockExports) ProxyOnRequestTrailers(contextID, trailers int32) (v1.Action, error) {
	_ = "STUB: not implemented"
	return *new(v1.Action), nil
}

// ProxyOnRequestTrailers indicates an expected call of ProxyOnRequestTrailers.
func (mr *MockExportsMockRecorder) ProxyOnRequestTrailers(contextID, trailers interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ProxyOnResponseBody mocks base method.
func (m *MockExports) ProxyOnResponseBody(contextID, bodyBufferLength, endOfStream int32) (v1.Action, error) {
	_ = "STUB: not implemented"
	return *new(v1.Action), nil
}

// ProxyOnResponseBody indicates an expected call of ProxyOnResponseBody.
func (mr *MockExportsMockRecorder) ProxyOnResponseBody(contextID, bodyBufferLength, endOfStream interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ProxyOnResponseHeaders mocks base method.
func (m *MockExports) ProxyOnResponseHeaders(contextID, headers, endOfStream int32) (v1.Action, error) {
	_ = "STUB: not implemented"
	return *new(v1.Action), nil
}

// ProxyOnResponseHeaders indicates an expected call of ProxyOnResponseHeaders.
func (mr *MockExportsMockRecorder) ProxyOnResponseHeaders(contextID, headers, endOfStream interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ProxyOnResponseMetadata mocks base method.
func (m *MockExports) ProxyOnResponseMetadata(contextID, nElements int32) (v1.Action, error) {
	_ = "STUB: not implemented"
	return *new(v1.Action), nil
}

// ProxyOnResponseMetadata indicates an expected call of ProxyOnResponseMetadata.
func (mr *MockExportsMockRecorder) ProxyOnResponseMetadata(contextID, nElements interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ProxyOnResponseTrailers mocks base method.
func (m *MockExports) ProxyOnResponseTrailers(contextID, trailers int32) (v1.Action, error) {
	_ = "STUB: not implemented"
	return *new(v1.Action), nil
}

// ProxyOnResponseTrailers indicates an expected call of ProxyOnResponseTrailers.
func (mr *MockExportsMockRecorder) ProxyOnResponseTrailers(contextID, trailers interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ProxyOnTick mocks base method.
func (m *MockExports) ProxyOnTick(rootContextID int32) error { _ = "STUB: not implemented"; return nil }

// ProxyOnTick indicates an expected call of ProxyOnTick.
func (mr *MockExportsMockRecorder) ProxyOnTick(rootContextID interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ProxyOnUpstreamConnectionClose mocks base method.
func (m *MockExports) ProxyOnUpstreamConnectionClose(contextID, closeType int32) error {
	_ = "STUB: not implemented"
	return nil
}

// ProxyOnUpstreamConnectionClose indicates an expected call of ProxyOnUpstreamConnectionClose.
func (mr *MockExportsMockRecorder) ProxyOnUpstreamConnectionClose(contextID, closeType interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ProxyOnUpstreamData mocks base method.
func (m *MockExports) ProxyOnUpstreamData(contextID, dataLength, endOfStream int32) (v1.Action, error) {
	_ = "STUB: not implemented"
	return *new(v1.Action), nil
}

// ProxyOnUpstreamData indicates an expected call of ProxyOnUpstreamData.
func (mr *MockExportsMockRecorder) ProxyOnUpstreamData(contextID, dataLength, endOfStream interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ProxyOnVmStart mocks base method.
func (m *MockExports) ProxyOnVmStart(rootContextID, vmConfigurationSize int32) (int32, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

// ProxyOnVmStart indicates an expected call of ProxyOnVmStart.
func (mr *MockExportsMockRecorder) ProxyOnVmStart(rootContextID, vmConfigurationSize interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
